<?php

/**
 * This is the model base class for the table "lien_feuille".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LienFeuille".
 *
 * Columns in table "lien_feuille" available as properties of the model,
 * followed by relations of table "lien_feuille" available as properties of the model.
 *
 * @property integer $id_lien_feuille
 * @property integer $id_chemise
 * @property integer $id_feuille
 *
 * @property Feuille $idFeuille
 * @property Chemise $idChemise
 */
abstract class BaseLienFeuille extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'lien_feuille';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LienFeuille|LienFeuilles', $n);
	}

	public static function representingColumn() {
		return 'id_lien_feuille';
	}

	public function rules() {
		return array(
			array('id_chemise, id_feuille', 'required'),
			array('id_chemise, id_feuille', 'numerical', 'integerOnly'=>true),
			array('id_lien_feuille, id_chemise, id_feuille', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idFeuille' => array(self::BELONGS_TO, 'Feuille', 'id_feuille'),
			'idChemise' => array(self::BELONGS_TO, 'Chemise', 'id_chemise'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_lien_feuille' => Yii::t('app', 'Id Lien Feuille'),
			'id_chemise' => null,
			'id_feuille' => null,
			'idFeuille' => null,
			'idChemise' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_lien_feuille', $this->id_lien_feuille);
		$criteria->compare('id_chemise', $this->id_chemise);
		$criteria->compare('id_feuille', $this->id_feuille);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
