<?php

/**
 * This is the model base class for the table "club".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Club".
 *
 * Columns in table "club" available as properties of the model,
 * followed by relations of table "club" available as properties of the model.
 *
 * @property integer $id_club
 * @property integer $id_annu
 * @property string $abreviation
 * @property boolean $cotisation
 * @property integer $id_compte
 * @property boolean $actif
 * @property integer $code_ffvv
 *
 * @property TarifTypeDate[] $tarifTypeDates
 * @property TarifTypeTiers[] $tarifTypeTiers
 * @property Annuaire $idAnnu
 * @property Pilote[] $pilotes
 * @property TarifTypeTreuillee[] $tarifTypeTreuillees
 * @property DemandeStage[] $demandeStages
 */
abstract class BaseClub extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'club';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Club|Clubs', $n);
	}

	public static function representingColumn() {
		return 'abreviation';
	}

	public function rules() {
		return array(
			array('id_annu, id_compte', 'required'),
			array('id_annu, id_compte, code_ffvv', 'numerical', 'integerOnly'=>true),
			array('abreviation', 'length', 'max'=>30),
			array('cotisation, actif', 'safe'),
			array('abreviation, cotisation, actif, code_ffvv', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_club, id_annu, abreviation, cotisation, id_compte, actif, code_ffvv', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tarifTypeDates' => array(self::HAS_MANY, 'TarifTypeDate', 'id_club'),
			'tarifTypeTiers' => array(self::HAS_MANY, 'TarifTypeTiers', 'id_club'),
			'idAnnu' => array(self::BELONGS_TO, 'Annuaire', 'id_annu'),
			'pilotes' => array(self::HAS_MANY, 'Pilote', 'id_club'),
			'tarifTypeTreuillees' => array(self::HAS_MANY, 'TarifTypeTreuillee', 'id_club'),
			'demandeStages' => array(self::HAS_MANY, 'DemandeStage', 'id_club'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_club' => Yii::t('app', 'Id Club'),
			'id_annu' => null,
			'abreviation' => Yii::t('app', 'Abreviation'),
			'cotisation' => Yii::t('app', 'Cotisation'),
			'id_compte' => Yii::t('app', 'Id Compte'),
			'actif' => Yii::t('app', 'Actif'),
			'code_ffvv' => Yii::t('app', 'Code Ffvv'),
			'tarifTypeDates' => null,
			'tarifTypeTiers' => null,
			'idAnnu' => null,
			'pilotes' => null,
			'tarifTypeTreuillees' => null,
			'demandeStages' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_club', $this->id_club);
		$criteria->compare('id_annu', $this->id_annu);
		$criteria->compare('abreviation', $this->abreviation, true);
		$criteria->compare('cotisation', $this->cotisation);
		$criteria->compare('id_compte', $this->id_compte);
		$criteria->compare('actif', $this->actif);
		$criteria->compare('code_ffvv', $this->code_ffvv);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
