<?php

/**
 * This is the model base class for the table "tarif_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TarifType".
 *
 * Columns in table "tarif_type" available as properties of the model,
 * followed by relations of table "tarif_type" available as properties of the model.
 *
 * @property integer $id_tarif_type
 * @property string $nom_type
 * @property boolean $actif
 * @property integer $id_tarif_type_maitre
 *
 * @property TarifTypeDate[] $tarifTypeDates
 * @property TarifTypeHisto[] $tarifTypeHistos
 * @property TarifType $idTarifTypeMaitre
 * @property TarifType[] $tarifTypes
 */
abstract class BaseTarifType extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tarif_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TarifType|TarifTypes', $n);
	}

	public static function representingColumn() {
		return 'nom_type';
	}

	public function rules() {
		return array(
			array('nom_type', 'required'),
			array('id_tarif_type_maitre', 'numerical', 'integerOnly'=>true),
			array('nom_type', 'length', 'max'=>255),
			array('actif', 'safe'),
			array('actif, id_tarif_type_maitre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tarif_type, nom_type, actif, id_tarif_type_maitre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tarifTypeDates' => array(self::HAS_MANY, 'TarifTypeDate', 'id_tarif_type'),
			'tarifTypeHistos' => array(self::HAS_MANY, 'TarifTypeHisto', 'id_tarif_type'),
			'idTarifTypeMaitre' => array(self::BELONGS_TO, 'TarifType', 'id_tarif_type_maitre'),
			'tarifTypes' => array(self::HAS_MANY, 'TarifType', 'id_tarif_type_maitre'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tarif_type' => Yii::t('app', 'Id Tarif Type'),
			'nom_type' => Yii::t('app', 'Nom Type'),
			'actif' => Yii::t('app', 'Actif'),
			'id_tarif_type_maitre' => null,
			'tarifTypeDates' => null,
			'tarifTypeHistos' => null,
			'idTarifTypeMaitre' => null,
			'tarifTypes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tarif_type', $this->id_tarif_type);
		$criteria->compare('nom_type', $this->nom_type, true);
		$criteria->compare('actif', $this->actif);
		$criteria->compare('id_tarif_type_maitre', $this->id_tarif_type_maitre);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
