<?php

/**
 * This is the model base class for the table "piece".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Piece".
 *
 * Columns in table "piece" available as properties of the model,
 * followed by relations of table "piece" available as properties of the model.
 *
 * @property integer $id_piece
 * @property integer $id_exercice
 * @property integer $id_type_piece
 * @property string $no_piece
 * @property string $date_piece
 * @property string $date_echeance
 * @property string $date_valeur
 * @property string $nom
 * @property string $libelle
 * @property boolean $export
 * @property integer $id_chemise
 * @property string $date_creation
 * @property integer $id_utilisateur_creation
 * @property string $date_modification
 * @property integer $id_utilisateur_modification
 * @property integer $id_eve_pil
 * @property integer $id_pilote_vol
 *
 * @property RemiseBanque[] $remiseBanques
 * @property TypePiece $idTypePiece
 * @property Chemise $idChemise
 * @property Exercice $idExercice
 * @property Utilisateur $idUtilisateurCreation
 * @property Utilisateur $idUtilisateurModification
 * @property PiloteVol $idPiloteVol
 * @property EvenementPilote $idEvePil
 * @property PieceLigne[] $pieceLignes
 * @property BudgetValeur[] $budgetValeurs
 */
abstract class BasePiece extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'piece';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Piece|Pieces', $n);
	}

	public static function representingColumn() {
		return 'no_piece';
	}

	public function rules() {
		return array(
			array('id_exercice, id_type_piece, no_piece, date_piece, date_echeance, date_valeur, libelle, date_creation, id_utilisateur_creation, date_modification, id_utilisateur_modification', 'required'),
			array('id_exercice, id_type_piece, id_chemise, id_utilisateur_creation, id_utilisateur_modification, id_eve_pil, id_pilote_vol', 'numerical', 'integerOnly'=>true),
			array('no_piece', 'length', 'max'=>15),
			array('nom, libelle', 'length', 'max'=>120),
			array('export', 'safe'),
			array('nom, export, id_chemise, id_eve_pil, id_pilote_vol', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_piece, id_exercice, id_type_piece, no_piece, date_piece, date_echeance, date_valeur, nom, libelle, export, id_chemise, date_creation, id_utilisateur_creation, date_modification, id_utilisateur_modification, id_eve_pil, id_pilote_vol', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'remiseBanques' => array(self::HAS_MANY, 'RemiseBanque', 'id_piece'),
			'idTypePiece' => array(self::BELONGS_TO, 'TypePiece', 'id_type_piece'),
			'idChemise' => array(self::BELONGS_TO, 'Chemise', 'id_chemise'),
			'idExercice' => array(self::BELONGS_TO, 'Exercice', 'id_exercice'),
			'idUtilisateurCreation' => array(self::BELONGS_TO, 'Utilisateur', 'id_utilisateur_creation'),
			'idUtilisateurModification' => array(self::BELONGS_TO, 'Utilisateur', 'id_utilisateur_modification'),
			'idPiloteVol' => array(self::BELONGS_TO, 'PiloteVol', 'id_pilote_vol'),
			'idEvePil' => array(self::BELONGS_TO, 'EvenementPilote', 'id_eve_pil'),
			'pieceLignes' => array(self::HAS_MANY, 'PieceLigne', 'id_piece'),
			'budgetValeurs' => array(self::HAS_MANY, 'BudgetValeur', 'id_piece'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_piece' => Yii::t('app', 'Id Piece'),
			'id_exercice' => null,
			'id_type_piece' => null,
			'no_piece' => Yii::t('app', 'No Piece'),
			'date_piece' => Yii::t('app', 'Date Piece'),
			'date_echeance' => Yii::t('app', 'Date Echeance'),
			'date_valeur' => Yii::t('app', 'Date Valeur'),
			'nom' => Yii::t('app', 'Nom'),
			'libelle' => Yii::t('app', 'Libelle'),
			'export' => Yii::t('app', 'Export'),
			'id_chemise' => null,
			'date_creation' => Yii::t('app', 'Date Creation'),
			'id_utilisateur_creation' => null,
			'date_modification' => Yii::t('app', 'Date Modification'),
			'id_utilisateur_modification' => null,
			'id_eve_pil' => null,
			'id_pilote_vol' => null,
			'remiseBanques' => null,
			'idTypePiece' => null,
			'idChemise' => null,
			'idExercice' => null,
			'idUtilisateurCreation' => null,
			'idUtilisateurModification' => null,
			'idPiloteVol' => null,
			'idEvePil' => null,
			'pieceLignes' => null,
			'budgetValeurs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_piece', $this->id_piece);
		$criteria->compare('id_exercice', $this->id_exercice);
		$criteria->compare('id_type_piece', $this->id_type_piece);
		$criteria->compare('no_piece', $this->no_piece, true);
		$criteria->compare('date_piece', $this->date_piece, true);
		$criteria->compare('date_echeance', $this->date_echeance, true);
		$criteria->compare('date_valeur', $this->date_valeur, true);
		$criteria->compare('nom', $this->nom, true);
		$criteria->compare('libelle', $this->libelle, true);
		$criteria->compare('export', $this->export);
		$criteria->compare('id_chemise', $this->id_chemise);
		$criteria->compare('date_creation', $this->date_creation, true);
		$criteria->compare('id_utilisateur_creation', $this->id_utilisateur_creation);
		$criteria->compare('date_modification', $this->date_modification, true);
		$criteria->compare('id_utilisateur_modification', $this->id_utilisateur_modification);
		$criteria->compare('id_eve_pil', $this->id_eve_pil);
		$criteria->compare('id_pilote_vol', $this->id_pilote_vol);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
