<?php

/**
 * This is the model base class for the table "feuille".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Feuille".
 *
 * Columns in table "feuille" available as properties of the model,
 * followed by relations of table "feuille" available as properties of the model.
 *
 * @property integer $id_feuille
 * @property string $md5
 * @property integer $taille
 * @property string $contenu
 * @property string $mime_type
 * @property string $nom_fichier
 *
 * @property LienFeuille[] $lienFeuilles
 * @property Annuaire[] $annuaires
 * @property Annuaire[] $annuaires1
 * @property CourrielJoint[] $courrielJoints
 */
abstract class BaseFeuille extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'feuille';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Feuille|Feuilles', $n);
	}

	public static function representingColumn() {
		return 'md5';
	}

	public function rules() {
		return array(
			array('md5, contenu, mime_type, nom_fichier', 'required'),
			array('taille', 'numerical', 'integerOnly'=>true),
			array('md5', 'length', 'max'=>60),
			array('mime_type, nom_fichier', 'length', 'max'=>255),
			array('taille', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_feuille, md5, taille, contenu, mime_type, nom_fichier', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'lienFeuilles' => array(self::HAS_MANY, 'LienFeuille', 'id_feuille'),
			'annuaires' => array(self::HAS_MANY, 'Annuaire', 'id_photo'),
			'annuaires1' => array(self::HAS_MANY, 'Annuaire', 'id_photo_mini'),
			'courrielJoints' => array(self::HAS_MANY, 'CourrielJoint', 'id_feuille'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_feuille' => Yii::t('app', 'Id Feuille'),
			'md5' => Yii::t('app', 'Md5'),
			'taille' => Yii::t('app', 'Taille'),
			'contenu' => Yii::t('app', 'Contenu'),
			'mime_type' => Yii::t('app', 'Mime Type'),
			'nom_fichier' => Yii::t('app', 'Nom Fichier'),
			'lienFeuilles' => null,
			'annuaires' => null,
			'annuaires1' => null,
			'courrielJoints' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_feuille', $this->id_feuille);
		$criteria->compare('md5', $this->md5, true);
		$criteria->compare('taille', $this->taille);
		$criteria->compare('contenu', $this->contenu, true);
		$criteria->compare('mime_type', $this->mime_type, true);
		$criteria->compare('nom_fichier', $this->nom_fichier, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
