<?php

/**
 * This is the model base class for the table "tarif_tranche".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TarifTranche".
 *
 * Columns in table "tarif_tranche" available as properties of the model,
 * followed by relations of table "tarif_tranche" available as properties of the model.
 *
 * @property integer $id_tarif_tranche
 * @property string $nom_tranche
 * @property boolean $actif
 *
 * @property TarifTrancheItem[] $tarifTrancheItems
 * @property TarifTypeTreuillee[] $tarifTypeTreuillees
 * @property TarifTypeCond[] $tarifTypeConds
 * @property TarifTypeCond[] $tarifTypeConds1
 */
abstract class BaseTarifTranche extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tarif_tranche';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TarifTranche|TarifTranches', $n);
	}

	public static function representingColumn() {
		return 'nom_tranche';
	}

	public function rules() {
		return array(
			array('nom_tranche', 'required'),
			array('nom_tranche', 'length', 'max'=>255),
			array('actif', 'safe'),
			array('actif', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tarif_tranche, nom_tranche, actif', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tarifTrancheItems' => array(self::HAS_MANY, 'TarifTrancheItem', 'id_tarif_tranche'),
			'tarifTypeTreuillees' => array(self::HAS_MANY, 'TarifTypeTreuillee', 'id_tarif_tranche'),
			'tarifTypeConds' => array(self::HAS_MANY, 'TarifTypeCond', 'id_tarif_tranche_saison'),
			'tarifTypeConds1' => array(self::HAS_MANY, 'TarifTypeCond', 'id_tarif_tranche_vol'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tarif_tranche' => Yii::t('app', 'Id Tarif Tranche'),
			'nom_tranche' => Yii::t('app', 'Nom Tranche'),
			'actif' => Yii::t('app', 'Actif'),
			'tarifTrancheItems' => null,
			'tarifTypeTreuillees' => null,
			'tarifTypeConds' => null,
			'tarifTypeConds1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tarif_tranche', $this->id_tarif_tranche);
		$criteria->compare('nom_tranche', $this->nom_tranche, true);
		$criteria->compare('actif', $this->actif);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
