<?php

/**
 * This is the model base class for the table "tarif_type_histo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TarifTypeHisto".
 *
 * Columns in table "tarif_type_histo" available as properties of the model,
 * followed by relations of table "tarif_type_histo" available as properties of the model.
 *
 * @property integer $id_annu
 * @property string $date_application
 * @property integer $id_tarif_type
 * @property boolean $participation_journee
 *
 * @property Annuaire $idAnnu
 * @property TarifType $idTarifType
 */
abstract class BaseTarifTypeHisto extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tarif_type_histo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TarifTypeHisto|TarifTypeHistos', $n);
	}

	public static function representingColumn() {
		return 'date_application';
	}

	public function rules() {
		return array(
			array('date_application, id_tarif_type', 'required'),
			array('id_tarif_type', 'numerical', 'integerOnly'=>true),
			array('participation_journee', 'safe'),
			array('participation_journee', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_annu, date_application, id_tarif_type, participation_journee', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAnnu' => array(self::BELONGS_TO, 'Annuaire', 'id_annu'),
			'idTarifType' => array(self::BELONGS_TO, 'TarifType', 'id_tarif_type'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_annu' => null,
			'date_application' => Yii::t('app', 'Date Application'),
			'id_tarif_type' => null,
			'participation_journee' => Yii::t('app', 'Participation Journee'),
			'idAnnu' => null,
			'idTarifType' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_annu', $this->id_annu);
		$criteria->compare('date_application', $this->date_application, true);
		$criteria->compare('id_tarif_type', $this->id_tarif_type);
		$criteria->compare('participation_journee', $this->participation_journee);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
