<?php

/**
 * This is the model base class for the table "rapprochement".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Rapprochement".
 *
 * Columns in table "rapprochement" available as properties of the model,
 * followed by relations of table "rapprochement" available as properties of the model.
 *
 * @property integer $id_rapprochement
 * @property integer $id_banque
 * @property string $libelle
 * @property string $date_fin
 * @property string $montant_fin
 * @property integer $id_chemise
 *
 * @property PieceLigne[] $pieceLignes
 * @property Banque $idBanque
 * @property Chemise $idChemise
 */
abstract class BaseRapprochement extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'rapprochement';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Rapprochement|Rapprochements', $n);
	}

	public static function representingColumn() {
		return 'libelle';
	}

	public function rules() {
		return array(
			array('id_banque, libelle, date_fin', 'required'),
			array('id_banque, id_chemise', 'numerical', 'integerOnly'=>true),
			array('libelle', 'length', 'max'=>120),
			array('montant_fin', 'length', 'max'=>10),
			array('montant_fin, id_chemise', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_rapprochement, id_banque, libelle, date_fin, montant_fin, id_chemise', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pieceLignes' => array(self::HAS_MANY, 'PieceLigne', 'id_rapprochement'),
			'idBanque' => array(self::BELONGS_TO, 'Banque', 'id_banque'),
			'idChemise' => array(self::BELONGS_TO, 'Chemise', 'id_chemise'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_rapprochement' => Yii::t('app', 'Id Rapprochement'),
			'id_banque' => null,
			'libelle' => Yii::t('app', 'Libelle'),
			'date_fin' => Yii::t('app', 'Date Fin'),
			'montant_fin' => Yii::t('app', 'Montant Fin'),
			'id_chemise' => null,
			'pieceLignes' => null,
			'idBanque' => null,
			'idChemise' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_rapprochement', $this->id_rapprochement);
		$criteria->compare('id_banque', $this->id_banque);
		$criteria->compare('libelle', $this->libelle, true);
		$criteria->compare('date_fin', $this->date_fin, true);
		$criteria->compare('montant_fin', $this->montant_fin, true);
		$criteria->compare('id_chemise', $this->id_chemise);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
