<?php

/**
 * This is the model base class for the table "tarif_type_tiers".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TarifTypeTiers".
 *
 * Columns in table "tarif_type_tiers" available as properties of the model,
 * followed by relations of table "tarif_type_tiers" available as properties of the model.
 *
 * @property integer $id_tarif_type_cond
 * @property integer $id_club
 * @property string $pourcentage
 * @property string $max
 * @property string $max_vol
 *
 * @property Club $idClub
 * @property TarifTypeCond $idTarifTypeCond
 */
abstract class BaseTarifTypeTiers extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tarif_type_tiers';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TarifTypeTiers|TarifTypeTiers', $n);
	}

	public static function representingColumn() {
		return 'pourcentage';
	}

	public function rules() {
		return array(
			array('id_tarif_type_cond', 'required'),
			array('id_tarif_type_cond', 'numerical', 'integerOnly'=>true),
			array('pourcentage', 'length', 'max'=>5),
			array('max, max_vol', 'length', 'max'=>10),
			array('pourcentage, max, max_vol', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tarif_type_cond, id_club, pourcentage, max, max_vol', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idClub' => array(self::BELONGS_TO, 'Club', 'id_club'),
			'idTarifTypeCond' => array(self::BELONGS_TO, 'TarifTypeCond', 'id_tarif_type_cond'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tarif_type_cond' => null,
			'id_club' => null,
			'pourcentage' => Yii::t('app', 'Pourcentage'),
			'max' => Yii::t('app', 'Max'),
			'max_vol' => Yii::t('app', 'Max Vol'),
			'idClub' => null,
			'idTarifTypeCond' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tarif_type_cond', $this->id_tarif_type_cond);
		$criteria->compare('id_club', $this->id_club);
		$criteria->compare('pourcentage', $this->pourcentage, true);
		$criteria->compare('max', $this->max, true);
		$criteria->compare('max_vol', $this->max_vol, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
