<?php

/**
 * This is the model base class for the table "pilote_vol_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PiloteVolLog".
 *
 * Columns in table "pilote_vol_log" available as properties of the model,
 * followed by relations of table "pilote_vol_log" available as properties of the model.
 *
 * @property integer $id_pilote_vol_log
 * @property integer $id_annu
 * @property string $log_text
 *
 * @property Annuaire $idAnnu
 */
abstract class BasePiloteVolLog extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pilote_vol_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PiloteVolLog|PiloteVolLogs', $n);
	}

	public static function representingColumn() {
		return 'log_text';
	}

	public function rules() {
		return array(
			array('log_text', 'required'),
			array('log_text', 'length', 'max'=>1000),
			array('id_pilote_vol_log, id_annu, log_text', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAnnu' => array(self::BELONGS_TO, 'Annuaire', 'id_annu'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_pilote_vol_log' => Yii::t('app', 'Id Pilote Vol Log'),
			'id_annu' => null,
			'log_text' => Yii::t('app', 'Log Text'),
			'idAnnu' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_pilote_vol_log', $this->id_pilote_vol_log);
		$criteria->compare('id_annu', $this->id_annu);
		$criteria->compare('log_text', $this->log_text, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
