<?php

/**
 * This is the model base class for the table "aeronef_position".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AeronefPosition".
 *
 * Columns in table "aeronef_position" available as properties of the model,
 * followed by relations of table "aeronef_position" available as properties of the model.
 *
 * @property integer $id_aeronef
 * @property string $date_heure
 * @property string $imei
 * @property string $igc
 * @property string $nmea
 * @property integer $vitesse
 * @property string $debug_donnees
 *
 * @property Aeronef $idAeronef
 */
abstract class BaseAeronefPosition extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'aeronef_position';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AeronefPosition|AeronefPositions', $n);
	}

	public static function representingColumn() {
		return 'imei';
	}

	public function rules() {
		return array(
			array('date_heure, imei, igc, nmea, debug_donnees', 'required'),
			array('vitesse', 'numerical', 'integerOnly'=>true),
			array('imei', 'length', 'max'=>60),
			array('igc, nmea', 'length', 'max'=>1000),
			array('debug_donnees', 'length', 'max'=>4000),
			array('vitesse', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_aeronef, date_heure, imei, igc, nmea, vitesse, debug_donnees', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_aeronef' => null,
			'date_heure' => Yii::t('app', 'Date Heure'),
			'imei' => Yii::t('app', 'Imei'),
			'igc' => Yii::t('app', 'Igc'),
			'nmea' => Yii::t('app', 'Nmea'),
			'vitesse' => Yii::t('app', 'Vitesse'),
			'debug_donnees' => Yii::t('app', 'Debug Donnees'),
			'idAeronef' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('date_heure', $this->date_heure, true);
		$criteria->compare('imei', $this->imei, true);
		$criteria->compare('igc', $this->igc, true);
		$criteria->compare('nmea', $this->nmea, true);
		$criteria->compare('vitesse', $this->vitesse);
		$criteria->compare('debug_donnees', $this->debug_donnees, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
