<?php

/**
 * This is the model base class for the table "traduction".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Traduction".
 *
 * Columns in table "traduction" available as properties of the model,
 * followed by relations of table "traduction" available as properties of the model.
 *
 * @property integer $id_traduction
 * @property string $nom_table
 * @property integer $id
 * @property string $cle
 * @property string $nom_champ
 * @property integer $id_langue
 * @property string $expression_char
 * @property string $expression_text
 *
 * @property Langue $idLangue
 */
abstract class BaseTraduction extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'traduction';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Traduction|Traductions', $n);
	}

	public static function representingColumn() {
		return 'nom_table';
	}

	public function rules() {
		return array(
			array('nom_table, nom_champ, id_langue', 'required'),
			array('id, id_langue', 'numerical', 'integerOnly'=>true),
			array('nom_table, nom_champ', 'length', 'max'=>60),
			array('cle', 'length', 'max'=>255),
			array('expression_char', 'length', 'max'=>1000),
			array('expression_text', 'safe'),
			array('id, cle, expression_char, expression_text', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_traduction, nom_table, id, cle, nom_champ, id_langue, expression_char, expression_text', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idLangue' => array(self::BELONGS_TO, 'Langue', 'id_langue'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_traduction' => Yii::t('app', 'Id Traduction'),
			'nom_table' => Yii::t('app', 'Nom Table'),
			'id' => Yii::t('app', 'ID'),
			'cle' => Yii::t('app', 'Cle'),
			'nom_champ' => Yii::t('app', 'Nom Champ'),
			'id_langue' => null,
			'expression_char' => Yii::t('app', 'Expression Char'),
			'expression_text' => Yii::t('app', 'Expression Text'),
			'idLangue' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_traduction', $this->id_traduction);
		$criteria->compare('nom_table', $this->nom_table, true);
		$criteria->compare('id', $this->id);
		$criteria->compare('cle', $this->cle, true);
		$criteria->compare('nom_champ', $this->nom_champ, true);
		$criteria->compare('id_langue', $this->id_langue);
		$criteria->compare('expression_char', $this->expression_char, true);
		$criteria->compare('expression_text', $this->expression_text, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
