<?php

/**
 * This is the model base class for the table "aeronef_activite".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AeronefActivite".
 *
 * Columns in table "aeronef_activite" available as properties of the model,
 * followed by relations of table "aeronef_activite" available as properties of the model.
 *
 * @property integer $id_aeronef_activite
 * @property integer $id_aeronef
 * @property string $date_activite
 * @property integer $heures_vol
 * @property integer $remorques
 * @property integer $treuillees
 * @property integer $autonomes
 * @property integer $heures_moteur
 * @property integer $crochet
 * @property boolean $envoye
 *
 * @property Aeronef $idAeronef
 */
abstract class BaseAeronefActivite extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'aeronef_activite';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AeronefActivite|AeronefActivites', $n);
	}

	public static function representingColumn() {
		return 'date_activite';
	}

	public function rules() {
		return array(
			array('id_aeronef, date_activite', 'required'),
			array('id_aeronef, heures_vol, remorques, treuillees, autonomes, heures_moteur, crochet', 'numerical', 'integerOnly'=>true),
			array('envoye', 'safe'),
			array('heures_vol, remorques, treuillees, autonomes, heures_moteur, crochet, envoye', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_aeronef_activite, id_aeronef, date_activite, heures_vol, remorques, treuillees, autonomes, heures_moteur, crochet, envoye', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_aeronef_activite' => Yii::t('app', 'Id Aeronef Activite'),
			'id_aeronef' => null,
			'date_activite' => Yii::t('app', 'Date Activite'),
			'heures_vol' => Yii::t('app', 'Heures Vol'),
			'remorques' => Yii::t('app', 'Remorques'),
			'treuillees' => Yii::t('app', 'Treuillees'),
			'autonomes' => Yii::t('app', 'Autonomes'),
			'heures_moteur' => Yii::t('app', 'Heures Moteur'),
			'crochet' => Yii::t('app', 'Crochet'),
			'envoye' => Yii::t('app', 'Envoye'),
			'idAeronef' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_aeronef_activite', $this->id_aeronef_activite);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('date_activite', $this->date_activite, true);
		$criteria->compare('heures_vol', $this->heures_vol);
		$criteria->compare('remorques', $this->remorques);
		$criteria->compare('treuillees', $this->treuillees);
		$criteria->compare('autonomes', $this->autonomes);
		$criteria->compare('heures_moteur', $this->heures_moteur);
		$criteria->compare('crochet', $this->crochet);
		$criteria->compare('envoye', $this->envoye);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
