<?php

/**
 * This is the model base class for the table "compte".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Compte".
 *
 * Columns in table "compte" available as properties of the model,
 * followed by relations of table "compte" available as properties of the model.
 *
 * @property integer $id_compte
 * @property string $code
 * @property string $libelle
 * @property boolean $titre
 * @property boolean $actif
 * @property boolean $est_imputable
 * @property integer $id_classeur
 * @property integer $id_annu
 *
 * @property PieceLigne[] $pieceLignes
 * @property Classeur $idClasseur
 * @property Annuaire $idAnnu
 * @property Pilote[] $pilotes
 * @property Banque[] $banques
 * @property CompteInterne[] $compteInternes
 * @property CompteSolde[] $compteSoldes
 */
abstract class BaseCompte extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'compte';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Compte|Comptes', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, libelle', 'required'),
			array('id_classeur, id_annu', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>10),
			array('libelle', 'length', 'max'=>120),
			array('titre, actif, est_imputable', 'safe'),
			array('titre, actif, est_imputable, id_classeur, id_annu', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_compte, code, libelle, titre, actif, est_imputable, id_classeur, id_annu', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pieceLignes' => array(self::HAS_MANY, 'PieceLigne', 'id_compte'),
			'idClasseur' => array(self::BELONGS_TO, 'Classeur', 'id_classeur'),
			'idAnnu' => array(self::BELONGS_TO, 'Annuaire', 'id_annu'),
			'pilotes' => array(self::HAS_MANY, 'Pilote', 'id_compte'),
			'banques' => array(self::HAS_MANY, 'Banque', 'id_compte'),
			'compteInternes' => array(self::HAS_MANY, 'CompteInterne', 'id_compte'),
			'compteSoldes' => array(self::HAS_MANY, 'CompteSolde', 'id_compte'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_compte' => Yii::t('app', 'Id Compte'),
			'code' => Yii::t('app', 'Code'),
			'libelle' => Yii::t('app', 'Libelle'),
			'titre' => Yii::t('app', 'Titre'),
			'actif' => Yii::t('app', 'Actif'),
			'est_imputable' => Yii::t('app', 'Est Imputable'),
			'id_classeur' => null,
			'id_annu' => null,
			'pieceLignes' => null,
			'idClasseur' => null,
			'idAnnu' => null,
			'pilotes' => null,
			'banques' => null,
			'compteInternes' => null,
			'compteSoldes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_compte', $this->id_compte);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('libelle', $this->libelle, true);
		$criteria->compare('titre', $this->titre);
		$criteria->compare('actif', $this->actif);
		$criteria->compare('est_imputable', $this->est_imputable);
		$criteria->compare('id_classeur', $this->id_classeur);
		$criteria->compare('id_annu', $this->id_annu);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
