<?php

/**
 * This is the model base class for the table "aeronef_imei".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AeronefImei".
 *
 * Columns in table "aeronef_imei" available as properties of the model,
 * followed by relations of table "aeronef_imei" available as properties of the model.
 *
 * @property integer $id_aeronef_imei
 * @property integer $id_aeronef
 * @property string $imei
 * @property integer $interval_emission
 * @property integer $pos_minute
 * @property boolean $debug_trace
 * @property string $donnees
 *
 * @property Aeronef $idAeronef
 */
abstract class BaseAeronefImei extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'aeronef_imei';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AeronefImei|AeronefImeis', $n);
	}

	public static function representingColumn() {
		return 'imei';
	}

	public function rules() {
		return array(
			array('id_aeronef, imei', 'required'),
			array('id_aeronef, interval_emission, pos_minute', 'numerical', 'integerOnly'=>true),
			array('imei', 'length', 'max'=>60),
			array('donnees', 'length', 'max'=>1000),
			array('debug_trace', 'safe'),
			array('interval_emission, pos_minute, debug_trace, donnees', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_aeronef_imei, id_aeronef, imei, interval_emission, pos_minute, debug_trace, donnees', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_aeronef_imei' => Yii::t('app', 'Id Aeronef Imei'),
			'id_aeronef' => null,
			'imei' => Yii::t('app', 'Imei'),
			'interval_emission' => Yii::t('app', 'Interval Emission'),
			'pos_minute' => Yii::t('app', 'Pos Minute'),
			'debug_trace' => Yii::t('app', 'Debug Trace'),
			'donnees' => Yii::t('app', 'Donnees'),
			'idAeronef' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_aeronef_imei', $this->id_aeronef_imei);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('imei', $this->imei, true);
		$criteria->compare('interval_emission', $this->interval_emission);
		$criteria->compare('pos_minute', $this->pos_minute);
		$criteria->compare('debug_trace', $this->debug_trace);
		$criteria->compare('donnees', $this->donnees, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
