<?php

/**
 * This is the model base class for the table "compte_solde".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompteSolde".
 *
 * Columns in table "compte_solde" available as properties of the model,
 * followed by relations of table "compte_solde" available as properties of the model.
 *
 * @property integer $id_compte_solde
 * @property integer $id_compte
 * @property string $date_solde
 * @property string $debit
 * @property string $credit
 *
 * @property Compte $idCompte
 */
abstract class BaseCompteSolde extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'compte_solde';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CompteSolde|CompteSoldes', $n);
	}

	public static function representingColumn() {
		return 'date_solde';
	}

	public function rules() {
		return array(
			array('id_compte, date_solde', 'required'),
			array('id_compte', 'numerical', 'integerOnly'=>true),
			array('debit, credit', 'length', 'max'=>10),
			array('debit, credit', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_compte_solde, id_compte, date_solde, debit, credit', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCompte' => array(self::BELONGS_TO, 'Compte', 'id_compte'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_compte_solde' => Yii::t('app', 'Id Compte Solde'),
			'id_compte' => null,
			'date_solde' => Yii::t('app', 'Date Solde'),
			'debit' => Yii::t('app', 'Debit'),
			'credit' => Yii::t('app', 'Credit'),
			'idCompte' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_compte_solde', $this->id_compte_solde);
		$criteria->compare('id_compte', $this->id_compte);
		$criteria->compare('date_solde', $this->date_solde, true);
		$criteria->compare('debit', $this->debit, true);
		$criteria->compare('credit', $this->credit, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
