<?php

/**
 * This is the model base class for the table "journal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Journal".
 *
 * Columns in table "journal" available as properties of the model,
 * followed by relations of table "journal" available as properties of the model.
 *
 * @property integer $id_journal
 * @property string $code
 * @property string $libelle
 *
 * @property TypePiece[] $typePieces
 */
abstract class BaseJournal extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'journal';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Journal|Journals', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, libelle', 'required'),
			array('code', 'length', 'max'=>5),
			array('libelle', 'length', 'max'=>120),
			array('id_journal, code, libelle', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'typePieces' => array(self::HAS_MANY, 'TypePiece', 'id_journal'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_journal' => Yii::t('app', 'Id Journal'),
			'code' => Yii::t('app', 'Code'),
			'libelle' => Yii::t('app', 'Libelle'),
			'typePieces' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_journal', $this->id_journal);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('libelle', $this->libelle, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
