<?php

/**
 * This is the model base class for the table "aeronef_situation_benef".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AeronefSituationBenef".
 *
 * Columns in table "aeronef_situation_benef" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_aeronef_situation
 * @property integer $id_annu
 * @property string $pourcentage
 * @property boolean $paye_vol
 * @property integer $id_tarif_type
 *
 */
abstract class BaseAeronefSituationBenef extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'aeronef_situation_benef';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AeronefSituationBenef|AeronefSituationBenefs', $n);
	}

	public static function representingColumn() {
		return array(
			'id_aeronef_situation',
			'id_annu',
		);
	}

	public function rules() {
		return array(
			array('id_aeronef_situation, id_annu', 'required'),
			array('id_aeronef_situation, id_annu, id_tarif_type', 'numerical', 'integerOnly'=>true),
			array('pourcentage', 'length', 'max'=>5),
			array('paye_vol', 'safe'),
			array('pourcentage, paye_vol, id_tarif_type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_aeronef_situation, id_annu, pourcentage, paye_vol, id_tarif_type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_aeronef_situation' => null,
			'id_annu' => null,
			'pourcentage' => Yii::t('app', 'Pourcentage'),
			'paye_vol' => Yii::t('app', 'Paye Vol'),
			'id_tarif_type' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_aeronef_situation', $this->id_aeronef_situation);
		$criteria->compare('id_annu', $this->id_annu);
		$criteria->compare('pourcentage', $this->pourcentage, true);
		$criteria->compare('paye_vol', $this->paye_vol);
		$criteria->compare('id_tarif_type', $this->id_tarif_type);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
