<?php

/**
 * This is the model base class for the table "courriel".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Courriel".
 *
 * Columns in table "courriel" available as properties of the model,
 * followed by relations of table "courriel" available as properties of the model.
 *
 * @property integer $id_courriel
 * @property integer $id_utilisateur
 * @property string $date_creation
 * @property string $date_envoi
 * @property string $courriel_from
 * @property string $sujet
 * @property string $text_html
 * @property string $priorite
 *
 * @property Utilisateur $idUtilisateur
 * @property CourrielJoint[] $courrielJoints
 * @property CourrielTo[] $courrielTos
 */
abstract class BaseCourriel extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'courriel';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Courriel|Courriels', $n);
	}

	public static function representingColumn() {
		return 'date_creation';
	}

	public function rules() {
		return array(
			array('date_creation, courriel_from, sujet, text_html', 'required'),
			array('courriel_from', 'length', 'max'=>60),
			array('sujet', 'length', 'max'=>255),
			array('priorite', 'length', 'max'=>1),
			array('date_envoi', 'safe'),
			array('date_envoi, priorite', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_courriel, id_utilisateur, date_creation, date_envoi, courriel_from, sujet, text_html, priorite', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idUtilisateur' => array(self::BELONGS_TO, 'Utilisateur', 'id_utilisateur'),
			'courrielJoints' => array(self::HAS_MANY, 'CourrielJoint', 'id_courriel'),
			'courrielTos' => array(self::HAS_MANY, 'CourrielTo', 'id_courriel'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_courriel' => Yii::t('app', 'Id Courriel'),
			'id_utilisateur' => null,
			'date_creation' => Yii::t('app', 'Date Creation'),
			'date_envoi' => Yii::t('app', 'Date Envoi'),
			'courriel_from' => Yii::t('app', 'Courriel From'),
			'sujet' => Yii::t('app', 'Sujet'),
			'text_html' => Yii::t('app', 'Text Html'),
			'priorite' => Yii::t('app', 'Priorite'),
			'idUtilisateur' => null,
			'courrielJoints' => null,
			'courrielTos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_courriel', $this->id_courriel);
		$criteria->compare('id_utilisateur', $this->id_utilisateur);
		$criteria->compare('date_creation', $this->date_creation, true);
		$criteria->compare('date_envoi', $this->date_envoi, true);
		$criteria->compare('courriel_from', $this->courriel_from, true);
		$criteria->compare('sujet', $this->sujet, true);
		$criteria->compare('text_html', $this->text_html, true);
		$criteria->compare('priorite', $this->priorite, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
