<?php

/**
 * This is the model base class for the table "tarif_cat_aeronef".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TarifCatAeronef".
 *
 * Columns in table "tarif_cat_aeronef" available as properties of the model,
 * followed by relations of table "tarif_cat_aeronef" available as properties of the model.
 *
 * @property integer $id_tarif_cat_aeronef
 * @property string $nom_categorie
 *
 * @property ForfaitModele[] $forfaitModeles
 * @property AeronefSituation[] $aeronefSituations
 * @property TarifTypeDate[] $tarifTypeDates
 */
abstract class BaseTarifCatAeronef extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tarif_cat_aeronef';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TarifCatAeronef|TarifCatAeronefs', $n);
	}

	public static function representingColumn() {
		return 'nom_categorie';
	}

	public function rules() {
		return array(
			array('nom_categorie', 'required'),
			array('nom_categorie', 'length', 'max'=>255),
			array('id_tarif_cat_aeronef, nom_categorie', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'forfaitModeles' => array(self::MANY_MANY, 'ForfaitModele', 'forfait_modele_cat_complement(id_tarif_cat_aeronef, id_forfait_modele)'),
			'aeronefSituations' => array(self::HAS_MANY, 'AeronefSituation', 'id_tarif_cat_aeronef'),
			'tarifTypeDates' => array(self::HAS_MANY, 'TarifTypeDate', 'id_tarif_cat_aeronef'),
		);
	}

	public function pivotModels() {
		return array(
			'forfaitModeles' => 'ForfaitModeleCatComplement',
		);
	}

	public function attributeLabels() {
		return array(
			'id_tarif_cat_aeronef' => Yii::t('app', 'Id Tarif Cat Aeronef'),
			'nom_categorie' => Yii::t('app', 'Nom Categorie'),
			'forfaitModeles' => null,
			'aeronefSituations' => null,
			'tarifTypeDates' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tarif_cat_aeronef', $this->id_tarif_cat_aeronef);
		$criteria->compare('nom_categorie', $this->nom_categorie, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
