<?php

/**
 * This is the model base class for the table "tarif_type_cond".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TarifTypeCond".
 *
 * Columns in table "tarif_type_cond" available as properties of the model,
 * followed by relations of table "tarif_type_cond" available as properties of the model.
 *
 * @property integer $id_tarif_type_cond
 * @property integer $id_tarif_type_date
 * @property integer $id_tarif_type_vol
 * @property string $partie
 * @property string $prix_place_vol
 * @property string $prix_heure
 * @property string $prix_unite
 * @property string $coef_forfait
 * @property boolean $hors_forfait
 * @property integer $id_tarif_tranche_vol
 * @property integer $id_tarif_tranche_saison
 *
 * @property TarifTypeTiers $tarifTypeTiers
 * @property TarifTranche $idTarifTrancheSaison
 * @property TarifTranche $idTarifTrancheVol
 * @property TarifTypeDate $idTarifTypeDate
 * @property TarifTypeVol $idTarifTypeVol
 */
abstract class BaseTarifTypeCond extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tarif_type_cond';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TarifTypeCond|TarifTypeConds', $n);
	}

	public static function representingColumn() {
		return 'partie';
	}

	public function rules() {
		return array(
			array('id_tarif_type_date, id_tarif_type_vol', 'required'),
			array('id_tarif_type_date, id_tarif_type_vol, id_tarif_tranche_vol, id_tarif_tranche_saison', 'numerical', 'integerOnly'=>true),
			array('partie, prix_place_vol', 'length', 'max'=>1),
			array('prix_heure, prix_unite', 'length', 'max'=>10),
			array('coef_forfait', 'length', 'max'=>5),
			array('hors_forfait', 'safe'),
			array('partie, prix_place_vol, prix_heure, prix_unite, coef_forfait, hors_forfait, id_tarif_tranche_vol, id_tarif_tranche_saison', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tarif_type_cond, id_tarif_type_date, id_tarif_type_vol, partie, prix_place_vol, prix_heure, prix_unite, coef_forfait, hors_forfait, id_tarif_tranche_vol, id_tarif_tranche_saison', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tarifTypeTiers' => array(self::HAS_ONE, 'TarifTypeTiers', 'id_tarif_type_cond'),
			'idTarifTrancheSaison' => array(self::BELONGS_TO, 'TarifTranche', 'id_tarif_tranche_saison'),
			'idTarifTrancheVol' => array(self::BELONGS_TO, 'TarifTranche', 'id_tarif_tranche_vol'),
			'idTarifTypeDate' => array(self::BELONGS_TO, 'TarifTypeDate', 'id_tarif_type_date'),
			'idTarifTypeVol' => array(self::BELONGS_TO, 'TarifTypeVol', 'id_tarif_type_vol'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tarif_type_cond' => Yii::t('app', 'Id Tarif Type Cond'),
			'id_tarif_type_date' => null,
			'id_tarif_type_vol' => null,
			'partie' => Yii::t('app', 'Partie'),
			'prix_place_vol' => Yii::t('app', 'Prix Place Vol'),
			'prix_heure' => Yii::t('app', 'Prix Heure'),
			'prix_unite' => Yii::t('app', 'Prix Unite'),
			'coef_forfait' => Yii::t('app', 'Coef Forfait'),
			'hors_forfait' => Yii::t('app', 'Hors Forfait'),
			'id_tarif_tranche_vol' => null,
			'id_tarif_tranche_saison' => null,
			'tarifTypeTiers' => null,
			'idTarifTrancheSaison' => null,
			'idTarifTrancheVol' => null,
			'idTarifTypeDate' => null,
			'idTarifTypeVol' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tarif_type_cond', $this->id_tarif_type_cond);
		$criteria->compare('id_tarif_type_date', $this->id_tarif_type_date);
		$criteria->compare('id_tarif_type_vol', $this->id_tarif_type_vol);
		$criteria->compare('partie', $this->partie, true);
		$criteria->compare('prix_place_vol', $this->prix_place_vol, true);
		$criteria->compare('prix_heure', $this->prix_heure, true);
		$criteria->compare('prix_unite', $this->prix_unite, true);
		$criteria->compare('coef_forfait', $this->coef_forfait, true);
		$criteria->compare('hors_forfait', $this->hors_forfait);
		$criteria->compare('id_tarif_tranche_vol', $this->id_tarif_tranche_vol);
		$criteria->compare('id_tarif_tranche_saison', $this->id_tarif_tranche_saison);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
