<?php

/**
 * This is the model base class for the table "modele_document".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ModeleDocument".
 *
 * Columns in table "modele_document" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_mod_doc
 * @property string $code_modele
 * @property string $type_sortie
 * @property string $nom_modele
 * @property string $texte_modele
 *
 */
abstract class BaseModeleDocument extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'modele_document';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ModeleDocument|ModeleDocuments', $n);
	}

	public static function representingColumn() {
		return 'code_modele';
	}

	public function rules() {
		return array(
			array('code_modele, nom_modele, texte_modele', 'required'),
			array('code_modele', 'length', 'max'=>10),
			array('type_sortie', 'length', 'max'=>1),
			array('nom_modele', 'length', 'max'=>120),
			array('type_sortie', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_mod_doc, code_modele, type_sortie, nom_modele, texte_modele', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_mod_doc' => Yii::t('app', 'Id Mod Doc'),
			'code_modele' => Yii::t('app', 'Code Modele'),
			'type_sortie' => Yii::t('app', 'Type Sortie'),
			'nom_modele' => Yii::t('app', 'Nom Modele'),
			'texte_modele' => Yii::t('app', 'Texte Modele'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_mod_doc', $this->id_mod_doc);
		$criteria->compare('code_modele', $this->code_modele, true);
		$criteria->compare('type_sortie', $this->type_sortie, true);
		$criteria->compare('nom_modele', $this->nom_modele, true);
		$criteria->compare('texte_modele', $this->texte_modele, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
