<?php

/**
 * This is the model base class for the table "carnet_bord".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CarnetBord".
 *
 * Columns in table "carnet_bord" available as properties of the model,
 * followed by relations of table "carnet_bord" available as properties of the model.
 *
 * @property integer $id_carnet_bord
 * @property integer $id_aeronef
 * @property string $date_depart
 * @property integer $heures
 * @property integer $minutes
 * @property integer $lances
 * @property integer $treuillees
 * @property integer $tps_moteur
 * @property integer $prem_page
 * @property integer $nb_lignes
 * @property integer $dern_page
 * @property boolean $auto
 * @property boolean $maj
 *
 * @property Aeronef $idAeronef
 */
abstract class BaseCarnetBord extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'carnet_bord';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CarnetBord|CarnetBords', $n);
	}

	public static function representingColumn() {
		return 'date_depart';
	}

	public function rules() {
		return array(
			array('id_aeronef, date_depart', 'required'),
			array('id_aeronef, heures, minutes, lances, treuillees, tps_moteur, prem_page, nb_lignes, dern_page', 'numerical', 'integerOnly'=>true),
			array('auto, maj', 'safe'),
			array('heures, minutes, lances, treuillees, tps_moteur, prem_page, nb_lignes, dern_page, auto, maj', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_carnet_bord, id_aeronef, date_depart, heures, minutes, lances, treuillees, tps_moteur, prem_page, nb_lignes, dern_page, auto, maj', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_carnet_bord' => Yii::t('app', 'Id Carnet Bord'),
			'id_aeronef' => null,
			'date_depart' => Yii::t('app', 'Date Depart'),
			'heures' => Yii::t('app', 'Heures'),
			'minutes' => Yii::t('app', 'Minutes'),
			'lances' => Yii::t('app', 'Lances'),
			'treuillees' => Yii::t('app', 'Treuillees'),
			'tps_moteur' => Yii::t('app', 'Tps Moteur'),
			'prem_page' => Yii::t('app', 'Prem Page'),
			'nb_lignes' => Yii::t('app', 'Nb Lignes'),
			'dern_page' => Yii::t('app', 'Dern Page'),
			'auto' => Yii::t('app', 'Auto'),
			'maj' => Yii::t('app', 'Maj'),
			'idAeronef' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_carnet_bord', $this->id_carnet_bord);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('date_depart', $this->date_depart, true);
		$criteria->compare('heures', $this->heures);
		$criteria->compare('minutes', $this->minutes);
		$criteria->compare('lances', $this->lances);
		$criteria->compare('treuillees', $this->treuillees);
		$criteria->compare('tps_moteur', $this->tps_moteur);
		$criteria->compare('prem_page', $this->prem_page);
		$criteria->compare('nb_lignes', $this->nb_lignes);
		$criteria->compare('dern_page', $this->dern_page);
		$criteria->compare('auto', $this->auto);
		$criteria->compare('maj', $this->maj);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
