<?php

/**
 * This is the model base class for the table "concours".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Concours".
 *
 * Columns in table "concours" available as properties of the model,
 * followed by relations of table "concours" available as properties of the model.
 *
 * @property integer $id
 * @property string $libelle
 * @property string $date_debut
 * @property string $date_fin
 * @property integer $id_tarif_type_vol
 * @property integer $id_remorque
 *
 * @property TarifTypeVol $idTarifTypeVol
 * @property Remorque $idRemorque
 * @property Moyen[] $moyens
 * @property Classe[] $classes
 */
abstract class BaseConcours extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'concours';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Concours|Concours', $n);
	}

	public static function representingColumn() {
		return 'libelle';
	}

	public function rules() {
		return array(
			array('libelle, date_debut, date_fin', 'required'),
			array('id_tarif_type_vol, id_remorque', 'numerical', 'integerOnly'=>true),
			array('libelle', 'length', 'max'=>255),
			array('id_tarif_type_vol, id_remorque', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, libelle, date_debut, date_fin, id_tarif_type_vol, id_remorque', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idTarifTypeVol' => array(self::BELONGS_TO, 'TarifTypeVol', 'id_tarif_type_vol'),
			'idRemorque' => array(self::BELONGS_TO, 'Remorque', 'id_remorque'),
			'moyens' => array(self::HAS_MANY, 'Moyen', 'id_concours'),
			'classes' => array(self::HAS_MANY, 'Classe', 'id_concours'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'libelle' => Yii::t('app', 'Libelle'),
			'date_debut' => Yii::t('app', 'Date Debut'),
			'date_fin' => Yii::t('app', 'Date Fin'),
			'id_tarif_type_vol' => null,
			'id_remorque' => null,
			'idTarifTypeVol' => null,
			'idRemorque' => null,
			'moyens' => null,
			'classes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('libelle', $this->libelle, true);
		$criteria->compare('date_debut', $this->date_debut, true);
		$criteria->compare('date_fin', $this->date_fin, true);
		$criteria->compare('id_tarif_type_vol', $this->id_tarif_type_vol);
		$criteria->compare('id_remorque', $this->id_remorque);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
