<?php

/**
 * This is the model base class for the table "tarif_aeronef".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TarifAeronef".
 *
 * Columns in table "tarif_aeronef" available as properties of the model,
 * followed by relations of table "tarif_aeronef" available as properties of the model.
 *
 * @property integer $id_tarif_aeronef
 * @property integer $id_aeronef
 * @property string $date_application
 * @property string $coef_heure_forfait_junior
 * @property string $prix_heure_junior
 * @property string $coef_heure_forfait_senior
 * @property string $prix_heure_senior
 * @property string $prix_remorque_junior
 * @property string $prix_remorque_senior
 * @property string $prix_demi_remorque_junior
 * @property string $prix_demi_remorque_senior
 * @property string $prix_centieme_remorque_junior
 * @property string $prix_centieme_remorque_senior
 * @property string $prix_centieme_moteur_junior
 * @property string $prix_centieme_moteur_senior
 * @property string $prix_vi_club_au_treuil
 * @property string $prix_vi_club_en_remorque
 * @property string $prix_vi_club_autonome
 *
 * @property Aeronef $idAeronef
 * @property RemorqueurTemps[] $remorqueurTemps
 */
abstract class BaseTarifAeronef extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tarif_aeronef';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TarifAeronef|TarifAeronefs', $n);
	}

	public static function representingColumn() {
		return 'date_application';
	}

	public function rules() {
		return array(
			array('id_aeronef, date_application', 'required'),
			array('id_aeronef', 'numerical', 'integerOnly'=>true),
			array('coef_heure_forfait_junior, coef_heure_forfait_senior', 'length', 'max'=>5),
			array('prix_heure_junior, prix_heure_senior, prix_remorque_junior, prix_remorque_senior, prix_demi_remorque_junior, prix_demi_remorque_senior, prix_centieme_remorque_junior, prix_centieme_remorque_senior, prix_centieme_moteur_junior, prix_centieme_moteur_senior, prix_vi_club_au_treuil, prix_vi_club_en_remorque, prix_vi_club_autonome', 'length', 'max'=>10),
			array('coef_heure_forfait_junior, prix_heure_junior, coef_heure_forfait_senior, prix_heure_senior, prix_remorque_junior, prix_remorque_senior, prix_demi_remorque_junior, prix_demi_remorque_senior, prix_centieme_remorque_junior, prix_centieme_remorque_senior, prix_centieme_moteur_junior, prix_centieme_moteur_senior, prix_vi_club_au_treuil, prix_vi_club_en_remorque, prix_vi_club_autonome', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tarif_aeronef, id_aeronef, date_application, coef_heure_forfait_junior, prix_heure_junior, coef_heure_forfait_senior, prix_heure_senior, prix_remorque_junior, prix_remorque_senior, prix_demi_remorque_junior, prix_demi_remorque_senior, prix_centieme_remorque_junior, prix_centieme_remorque_senior, prix_centieme_moteur_junior, prix_centieme_moteur_senior, prix_vi_club_au_treuil, prix_vi_club_en_remorque, prix_vi_club_autonome', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
			'remorqueurTemps' => array(self::HAS_MANY, 'RemorqueurTemps', 'id_tarif_aeronef'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tarif_aeronef' => Yii::t('app', 'Id Tarif Aeronef'),
			'id_aeronef' => null,
			'date_application' => Yii::t('app', 'Date Application'),
			'coef_heure_forfait_junior' => Yii::t('app', 'Coef Heure Forfait Junior'),
			'prix_heure_junior' => Yii::t('app', 'Prix Heure Junior'),
			'coef_heure_forfait_senior' => Yii::t('app', 'Coef Heure Forfait Senior'),
			'prix_heure_senior' => Yii::t('app', 'Prix Heure Senior'),
			'prix_remorque_junior' => Yii::t('app', 'Prix Remorque Junior'),
			'prix_remorque_senior' => Yii::t('app', 'Prix Remorque Senior'),
			'prix_demi_remorque_junior' => Yii::t('app', 'Prix Demi Remorque Junior'),
			'prix_demi_remorque_senior' => Yii::t('app', 'Prix Demi Remorque Senior'),
			'prix_centieme_remorque_junior' => Yii::t('app', 'Prix Centieme Remorque Junior'),
			'prix_centieme_remorque_senior' => Yii::t('app', 'Prix Centieme Remorque Senior'),
			'prix_centieme_moteur_junior' => Yii::t('app', 'Prix Centieme Moteur Junior'),
			'prix_centieme_moteur_senior' => Yii::t('app', 'Prix Centieme Moteur Senior'),
			'prix_vi_club_au_treuil' => Yii::t('app', 'Prix Vi Club Au Treuil'),
			'prix_vi_club_en_remorque' => Yii::t('app', 'Prix Vi Club En Remorque'),
			'prix_vi_club_autonome' => Yii::t('app', 'Prix Vi Club Autonome'),
			'idAeronef' => null,
			'remorqueurTemps' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tarif_aeronef', $this->id_tarif_aeronef);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('date_application', $this->date_application, true);
		$criteria->compare('coef_heure_forfait_junior', $this->coef_heure_forfait_junior, true);
		$criteria->compare('prix_heure_junior', $this->prix_heure_junior, true);
		$criteria->compare('coef_heure_forfait_senior', $this->coef_heure_forfait_senior, true);
		$criteria->compare('prix_heure_senior', $this->prix_heure_senior, true);
		$criteria->compare('prix_remorque_junior', $this->prix_remorque_junior, true);
		$criteria->compare('prix_remorque_senior', $this->prix_remorque_senior, true);
		$criteria->compare('prix_demi_remorque_junior', $this->prix_demi_remorque_junior, true);
		$criteria->compare('prix_demi_remorque_senior', $this->prix_demi_remorque_senior, true);
		$criteria->compare('prix_centieme_remorque_junior', $this->prix_centieme_remorque_junior, true);
		$criteria->compare('prix_centieme_remorque_senior', $this->prix_centieme_remorque_senior, true);
		$criteria->compare('prix_centieme_moteur_junior', $this->prix_centieme_moteur_junior, true);
		$criteria->compare('prix_centieme_moteur_senior', $this->prix_centieme_moteur_senior, true);
		$criteria->compare('prix_vi_club_au_treuil', $this->prix_vi_club_au_treuil, true);
		$criteria->compare('prix_vi_club_en_remorque', $this->prix_vi_club_en_remorque, true);
		$criteria->compare('prix_vi_club_autonome', $this->prix_vi_club_autonome, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
