<?php

/**
 * This is the model base class for the table "plan_part".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PlanPart".
 *
 * Columns in table "plan_part" available as properties of the model,
 * followed by relations of table "plan_part" available as properties of the model.
 *
 * @property integer $id_plan_part
 * @property integer $id_plan_jour
 * @property integer $id_annu
 * @property integer $id_plan_contact
 * @property string $part_comment
 *
 * @property Annuaire $idAnnu
 * @property PlanContact $idPlanContact
 * @property PlanJour $idPlanJour
 */
abstract class BasePlanPart extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'plan_part';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PlanPart|PlanParts', $n);
	}

	public static function representingColumn() {
		return 'part_comment';
	}

	public function rules() {
		return array(
			array('id_plan_jour', 'required'),
			array('id_plan_jour, id_annu, id_plan_contact', 'numerical', 'integerOnly'=>true),
			array('part_comment', 'safe'),
			array('id_annu, id_plan_contact, part_comment', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_plan_part, id_plan_jour, id_annu, id_plan_contact, part_comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAnnu' => array(self::BELONGS_TO, 'Annuaire', 'id_annu'),
			'idPlanContact' => array(self::BELONGS_TO, 'PlanContact', 'id_plan_contact'),
			'idPlanJour' => array(self::BELONGS_TO, 'PlanJour', 'id_plan_jour'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_plan_part' => Yii::t('app', 'Id Plan Part'),
			'id_plan_jour' => null,
			'id_annu' => null,
			'id_plan_contact' => null,
			'part_comment' => Yii::t('app', 'Part Comment'),
			'idAnnu' => null,
			'idPlanContact' => null,
			'idPlanJour' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_plan_part', $this->id_plan_part);
		$criteria->compare('id_plan_jour', $this->id_plan_jour);
		$criteria->compare('id_annu', $this->id_annu);
		$criteria->compare('id_plan_contact', $this->id_plan_contact);
		$criteria->compare('part_comment', $this->part_comment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
