<?php

/**
 * This is the model base class for the table "cheque_emis".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ChequeEmis".
 *
 * Columns in table "cheque_emis" available as properties of the model,
 * followed by relations of table "cheque_emis" available as properties of the model.
 *
 * @property integer $id_cheque
 * @property integer $id_banque_chequier
 * @property integer $numero
 * @property integer $id_piece_ligne
 *
 * @property BanqueChequier $idBanqueChequier
 * @property PieceLigne $idPieceLigne
 */
abstract class BaseChequeEmis extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cheque_emis';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ChequeEmis|ChequeEmises', $n);
	}

	public static function representingColumn() {
		return 'id_cheque';
	}

	public function rules() {
		return array(
			array('id_banque_chequier', 'required'),
			array('id_banque_chequier, numero, id_piece_ligne', 'numerical', 'integerOnly'=>true),
			array('numero, id_piece_ligne', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_cheque, id_banque_chequier, numero, id_piece_ligne', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idBanqueChequier' => array(self::BELONGS_TO, 'BanqueChequier', 'id_banque_chequier'),
			'idPieceLigne' => array(self::BELONGS_TO, 'PieceLigne', 'id_piece_ligne'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_cheque' => Yii::t('app', 'Id Cheque'),
			'id_banque_chequier' => null,
			'numero' => Yii::t('app', 'Numero'),
			'id_piece_ligne' => null,
			'idBanqueChequier' => null,
			'idPieceLigne' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_cheque', $this->id_cheque);
		$criteria->compare('id_banque_chequier', $this->id_banque_chequier);
		$criteria->compare('numero', $this->numero);
		$criteria->compare('id_piece_ligne', $this->id_piece_ligne);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
