<?php

/**
 * This is the model base class for the table "demande_stage".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DemandeStage".
 *
 * Columns in table "demande_stage" available as properties of the model,
 * followed by relations of table "demande_stage" available as properties of the model.
 *
 * @property integer $id_demande_stage
 * @property integer $id_pilote
 * @property string $civilite
 * @property string $nom_prenom
 * @property string $adresse_1
 * @property string $adresse_2
 * @property string $code_postal
 * @property string $ville
 * @property string $pays
 * @property integer $id_langue
 * @property string $tel_perso
 * @property string $tel_mobile
 * @property string $tel_prof
 * @property string $e_mail_perso
 * @property string $date_naissance
 * @property string $lieu_naissance
 * @property integer $id_club
 * @property string $club_nom
 * @property string $club_adresse_1
 * @property string $club_adresse_2
 * @property string $club_code_postal
 * @property string $club_ville
 * @property string $club_pays
 * @property string $club_tel
 * @property string $club_e_mail
 * @property integer $id_contact
 * @property string $contact_nom_prenom
 * @property string $contact_tel_perso
 * @property string $contact_tel_mobile
 * @property string $contact_e_mail
 * @property integer $annee_debut
 * @property string $no_licence_pp
 * @property string $date_bpp_pratique
 * @property integer $heure_tot_pilote_vi
 * @property integer $heure_an_pilote_vi
 * @property integer $heures_montagne
 * @property string $date_visite_medicale
 * @property boolean $licence_assurance_ffvv
 * @property string $date_arrivee
 * @property string $date_depart
 * @property integer $id_aeronef
 * @property string $type_aeronef
 * @property string $no_serie
 * @property integer $annee_fabrication
 * @property string $immatriculation
 * @property string $no_concours
 * @property string $cdn
 * @property string $cen_validite
 * @property string $assurance_nom
 * @property string $assurance_police
 * @property string $assurance_echeance
 * @property boolean $treuillable
 * @property boolean $remorquable
 * @property boolean $turbo
 * @property boolean $autonome
 * @property boolean $balise
 * @property boolean $flarm
 * @property boolean $bandes_anti_col
 * @property string $remorque_type
 * @property string $remorque_immatriculation
 * @property integer $id_hebergement
 * @property string $hebergement_nom
 * @property string $hebergement_adresse_1
 * @property string $hebergement_adresse_2
 * @property string $hebergement_code_postal
 * @property string $hebergement_ville
 * @property string $hebergement_contact
 * @property string $hebergement_tel_perso
 * @property string $hebergement_tel_mobile
 * @property string $commentaire
 * @property string $date_time
 * @property boolean $refus
 * @property string $sexe
 * @property integer $id_planning_stage
 *
 * @property Pilote $idPilote
 * @property Aeronef $idAeronef
 * @property Annuaire $idContact
 * @property PlanningStage $idPlanningStage
 * @property Club $idClub
 * @property Langue $idLangue
 * @property Pays $pays0
 * @property Civilite $civilite0
 * @property Hebergement $idHebergement
 */
abstract class BaseDemandeStage extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'demande_stage';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DemandeStage|DemandeStages', $n);
	}

	public static function representingColumn() {
		return 'date_arrivee';
	}

	public function rules() {
		return array(
			array('id_langue, date_arrivee, date_depart, date_time', 'required'),
			array('id_pilote, id_langue, id_club, id_contact, annee_debut, heure_tot_pilote_vi, heure_an_pilote_vi, heures_montagne, id_aeronef, annee_fabrication, id_hebergement, id_planning_stage', 'numerical', 'integerOnly'=>true),
			array('civilite, no_concours', 'length', 'max'=>5),
			array('nom_prenom, adresse_1, adresse_2, ville, pays, e_mail_perso, lieu_naissance, club_nom, club_adresse_1, club_adresse_2, club_ville, club_pays, club_e_mail, contact_nom_prenom, contact_e_mail, type_aeronef, no_serie, cdn, assurance_nom, assurance_police, remorque_type, hebergement_nom, hebergement_adresse_1, hebergement_adresse_2, hebergement_ville, hebergement_contact', 'length', 'max'=>60),
			array('code_postal, club_code_postal, remorque_immatriculation, hebergement_code_postal', 'length', 'max'=>15),
			array('tel_perso, tel_mobile, tel_prof, club_tel, contact_tel_perso, contact_tel_mobile, hebergement_tel_perso, hebergement_tel_mobile', 'length', 'max'=>25),
			array('no_licence_pp', 'length', 'max'=>30),
			array('immatriculation', 'length', 'max'=>10),
			array('sexe', 'length', 'max'=>1),
			array('date_naissance, date_bpp_pratique, date_visite_medicale, licence_assurance_ffvv, cen_validite, assurance_echeance, treuillable, remorquable, turbo, autonome, balise, flarm, bandes_anti_col, commentaire, refus', 'safe'),
			array('id_pilote, civilite, nom_prenom, adresse_1, adresse_2, code_postal, ville, pays, tel_perso, tel_mobile, tel_prof, e_mail_perso, date_naissance, lieu_naissance, id_club, club_nom, club_adresse_1, club_adresse_2, club_code_postal, club_ville, club_pays, club_tel, club_e_mail, id_contact, contact_nom_prenom, contact_tel_perso, contact_tel_mobile, contact_e_mail, annee_debut, no_licence_pp, date_bpp_pratique, heure_tot_pilote_vi, heure_an_pilote_vi, heures_montagne, date_visite_medicale, licence_assurance_ffvv, id_aeronef, type_aeronef, no_serie, annee_fabrication, immatriculation, no_concours, cdn, cen_validite, assurance_nom, assurance_police, assurance_echeance, treuillable, remorquable, turbo, autonome, balise, flarm, bandes_anti_col, remorque_type, remorque_immatriculation, id_hebergement, hebergement_nom, hebergement_adresse_1, hebergement_adresse_2, hebergement_code_postal, hebergement_ville, hebergement_contact, hebergement_tel_perso, hebergement_tel_mobile, commentaire, refus, sexe, id_planning_stage', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_demande_stage, id_pilote, civilite, nom_prenom, adresse_1, adresse_2, code_postal, ville, pays, id_langue, tel_perso, tel_mobile, tel_prof, e_mail_perso, date_naissance, lieu_naissance, id_club, club_nom, club_adresse_1, club_adresse_2, club_code_postal, club_ville, club_pays, club_tel, club_e_mail, id_contact, contact_nom_prenom, contact_tel_perso, contact_tel_mobile, contact_e_mail, annee_debut, no_licence_pp, date_bpp_pratique, heure_tot_pilote_vi, heure_an_pilote_vi, heures_montagne, date_visite_medicale, licence_assurance_ffvv, date_arrivee, date_depart, id_aeronef, type_aeronef, no_serie, annee_fabrication, immatriculation, no_concours, cdn, cen_validite, assurance_nom, assurance_police, assurance_echeance, treuillable, remorquable, turbo, autonome, balise, flarm, bandes_anti_col, remorque_type, remorque_immatriculation, id_hebergement, hebergement_nom, hebergement_adresse_1, hebergement_adresse_2, hebergement_code_postal, hebergement_ville, hebergement_contact, hebergement_tel_perso, hebergement_tel_mobile, commentaire, date_time, refus, sexe, id_planning_stage', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPilote' => array(self::BELONGS_TO, 'Pilote', 'id_pilote'),
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
			'idContact' => array(self::BELONGS_TO, 'Annuaire', 'id_contact'),
			'idPlanningStage' => array(self::BELONGS_TO, 'PlanningStage', 'id_planning_stage'),
			'idClub' => array(self::BELONGS_TO, 'Club', 'id_club'),
			'idLangue' => array(self::BELONGS_TO, 'Langue', 'id_langue'),
			'pays0' => array(self::BELONGS_TO, 'Pays', 'pays'),
			'civilite0' => array(self::BELONGS_TO, 'Civilite', 'civilite'),
			'idHebergement' => array(self::BELONGS_TO, 'Hebergement', 'id_hebergement'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_demande_stage' => Yii::t('app', 'Id Demande Stage'),
			'id_pilote' => null,
			'civilite' => null,
			'nom_prenom' => Yii::t('app', 'Nom Prenom'),
			'adresse_1' => Yii::t('app', 'Adresse 1'),
			'adresse_2' => Yii::t('app', 'Adresse 2'),
			'code_postal' => Yii::t('app', 'Code Postal'),
			'ville' => Yii::t('app', 'Ville'),
			'pays' => null,
			'id_langue' => null,
			'tel_perso' => Yii::t('app', 'Tel Perso'),
			'tel_mobile' => Yii::t('app', 'Tel Mobile'),
			'tel_prof' => Yii::t('app', 'Tel Prof'),
			'e_mail_perso' => Yii::t('app', 'E Mail Perso'),
			'date_naissance' => Yii::t('app', 'Date Naissance'),
			'lieu_naissance' => Yii::t('app', 'Lieu Naissance'),
			'id_club' => null,
			'club_nom' => Yii::t('app', 'Club Nom'),
			'club_adresse_1' => Yii::t('app', 'Club Adresse 1'),
			'club_adresse_2' => Yii::t('app', 'Club Adresse 2'),
			'club_code_postal' => Yii::t('app', 'Club Code Postal'),
			'club_ville' => Yii::t('app', 'Club Ville'),
			'club_pays' => Yii::t('app', 'Club Pays'),
			'club_tel' => Yii::t('app', 'Club Tel'),
			'club_e_mail' => Yii::t('app', 'Club E Mail'),
			'id_contact' => null,
			'contact_nom_prenom' => Yii::t('app', 'Contact Nom Prenom'),
			'contact_tel_perso' => Yii::t('app', 'Contact Tel Perso'),
			'contact_tel_mobile' => Yii::t('app', 'Contact Tel Mobile'),
			'contact_e_mail' => Yii::t('app', 'Contact E Mail'),
			'annee_debut' => Yii::t('app', 'Annee Debut'),
			'no_licence_pp' => Yii::t('app', 'No Licence Pp'),
			'date_bpp_pratique' => Yii::t('app', 'Date Bpp Pratique'),
			'heure_tot_pilote_vi' => Yii::t('app', 'Heure Tot Pilote Vi'),
			'heure_an_pilote_vi' => Yii::t('app', 'Heure An Pilote Vi'),
			'heures_montagne' => Yii::t('app', 'Heures Montagne'),
			'date_visite_medicale' => Yii::t('app', 'Date Visite Medicale'),
			'licence_assurance_ffvv' => Yii::t('app', 'Licence Assurance Ffvv'),
			'date_arrivee' => Yii::t('app', 'Date Arrivee'),
			'date_depart' => Yii::t('app', 'Date Depart'),
			'id_aeronef' => null,
			'type_aeronef' => Yii::t('app', 'Type Aeronef'),
			'no_serie' => Yii::t('app', 'No Serie'),
			'annee_fabrication' => Yii::t('app', 'Annee Fabrication'),
			'immatriculation' => Yii::t('app', 'Immatriculation'),
			'no_concours' => Yii::t('app', 'No Concours'),
			'cdn' => Yii::t('app', 'Cdn'),
			'cen_validite' => Yii::t('app', 'Cen Validite'),
			'assurance_nom' => Yii::t('app', 'Assurance Nom'),
			'assurance_police' => Yii::t('app', 'Assurance Police'),
			'assurance_echeance' => Yii::t('app', 'Assurance Echeance'),
			'treuillable' => Yii::t('app', 'Treuillable'),
			'remorquable' => Yii::t('app', 'Remorquable'),
			'turbo' => Yii::t('app', 'Turbo'),
			'autonome' => Yii::t('app', 'Autonome'),
			'balise' => Yii::t('app', 'Balise'),
			'flarm' => Yii::t('app', 'Flarm'),
			'bandes_anti_col' => Yii::t('app', 'Bandes Anti Col'),
			'remorque_type' => Yii::t('app', 'Remorque Type'),
			'remorque_immatriculation' => Yii::t('app', 'Remorque Immatriculation'),
			'id_hebergement' => null,
			'hebergement_nom' => Yii::t('app', 'Hebergement Nom'),
			'hebergement_adresse_1' => Yii::t('app', 'Hebergement Adresse 1'),
			'hebergement_adresse_2' => Yii::t('app', 'Hebergement Adresse 2'),
			'hebergement_code_postal' => Yii::t('app', 'Hebergement Code Postal'),
			'hebergement_ville' => Yii::t('app', 'Hebergement Ville'),
			'hebergement_contact' => Yii::t('app', 'Hebergement Contact'),
			'hebergement_tel_perso' => Yii::t('app', 'Hebergement Tel Perso'),
			'hebergement_tel_mobile' => Yii::t('app', 'Hebergement Tel Mobile'),
			'commentaire' => Yii::t('app', 'Commentaire'),
			'date_time' => Yii::t('app', 'Date Time'),
			'refus' => Yii::t('app', 'Refus'),
			'sexe' => Yii::t('app', 'Sexe'),
			'id_planning_stage' => null,
			'idPilote' => null,
			'idAeronef' => null,
			'idContact' => null,
			'idPlanningStage' => null,
			'idClub' => null,
			'idLangue' => null,
			'pays0' => null,
			'civilite0' => null,
			'idHebergement' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_demande_stage', $this->id_demande_stage);
		$criteria->compare('id_pilote', $this->id_pilote);
		$criteria->compare('civilite', $this->civilite);
		$criteria->compare('nom_prenom', $this->nom_prenom, true);
		$criteria->compare('adresse_1', $this->adresse_1, true);
		$criteria->compare('adresse_2', $this->adresse_2, true);
		$criteria->compare('code_postal', $this->code_postal, true);
		$criteria->compare('ville', $this->ville, true);
		$criteria->compare('pays', $this->pays);
		$criteria->compare('id_langue', $this->id_langue);
		$criteria->compare('tel_perso', $this->tel_perso, true);
		$criteria->compare('tel_mobile', $this->tel_mobile, true);
		$criteria->compare('tel_prof', $this->tel_prof, true);
		$criteria->compare('e_mail_perso', $this->e_mail_perso, true);
		$criteria->compare('date_naissance', $this->date_naissance, true);
		$criteria->compare('lieu_naissance', $this->lieu_naissance, true);
		$criteria->compare('id_club', $this->id_club);
		$criteria->compare('club_nom', $this->club_nom, true);
		$criteria->compare('club_adresse_1', $this->club_adresse_1, true);
		$criteria->compare('club_adresse_2', $this->club_adresse_2, true);
		$criteria->compare('club_code_postal', $this->club_code_postal, true);
		$criteria->compare('club_ville', $this->club_ville, true);
		$criteria->compare('club_pays', $this->club_pays, true);
		$criteria->compare('club_tel', $this->club_tel, true);
		$criteria->compare('club_e_mail', $this->club_e_mail, true);
		$criteria->compare('id_contact', $this->id_contact);
		$criteria->compare('contact_nom_prenom', $this->contact_nom_prenom, true);
		$criteria->compare('contact_tel_perso', $this->contact_tel_perso, true);
		$criteria->compare('contact_tel_mobile', $this->contact_tel_mobile, true);
		$criteria->compare('contact_e_mail', $this->contact_e_mail, true);
		$criteria->compare('annee_debut', $this->annee_debut);
		$criteria->compare('no_licence_pp', $this->no_licence_pp, true);
		$criteria->compare('date_bpp_pratique', $this->date_bpp_pratique, true);
		$criteria->compare('heure_tot_pilote_vi', $this->heure_tot_pilote_vi);
		$criteria->compare('heure_an_pilote_vi', $this->heure_an_pilote_vi);
		$criteria->compare('heures_montagne', $this->heures_montagne);
		$criteria->compare('date_visite_medicale', $this->date_visite_medicale, true);
		$criteria->compare('licence_assurance_ffvv', $this->licence_assurance_ffvv);
		$criteria->compare('date_arrivee', $this->date_arrivee, true);
		$criteria->compare('date_depart', $this->date_depart, true);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('type_aeronef', $this->type_aeronef, true);
		$criteria->compare('no_serie', $this->no_serie, true);
		$criteria->compare('annee_fabrication', $this->annee_fabrication);
		$criteria->compare('immatriculation', $this->immatriculation, true);
		$criteria->compare('no_concours', $this->no_concours, true);
		$criteria->compare('cdn', $this->cdn, true);
		$criteria->compare('cen_validite', $this->cen_validite, true);
		$criteria->compare('assurance_nom', $this->assurance_nom, true);
		$criteria->compare('assurance_police', $this->assurance_police, true);
		$criteria->compare('assurance_echeance', $this->assurance_echeance, true);
		$criteria->compare('treuillable', $this->treuillable);
		$criteria->compare('remorquable', $this->remorquable);
		$criteria->compare('turbo', $this->turbo);
		$criteria->compare('autonome', $this->autonome);
		$criteria->compare('balise', $this->balise);
		$criteria->compare('flarm', $this->flarm);
		$criteria->compare('bandes_anti_col', $this->bandes_anti_col);
		$criteria->compare('remorque_type', $this->remorque_type, true);
		$criteria->compare('remorque_immatriculation', $this->remorque_immatriculation, true);
		$criteria->compare('id_hebergement', $this->id_hebergement);
		$criteria->compare('hebergement_nom', $this->hebergement_nom, true);
		$criteria->compare('hebergement_adresse_1', $this->hebergement_adresse_1, true);
		$criteria->compare('hebergement_adresse_2', $this->hebergement_adresse_2, true);
		$criteria->compare('hebergement_code_postal', $this->hebergement_code_postal, true);
		$criteria->compare('hebergement_ville', $this->hebergement_ville, true);
		$criteria->compare('hebergement_contact', $this->hebergement_contact, true);
		$criteria->compare('hebergement_tel_perso', $this->hebergement_tel_perso, true);
		$criteria->compare('hebergement_tel_mobile', $this->hebergement_tel_mobile, true);
		$criteria->compare('commentaire', $this->commentaire, true);
		$criteria->compare('date_time', $this->date_time, true);
		$criteria->compare('refus', $this->refus);
		$criteria->compare('sexe', $this->sexe, true);
		$criteria->compare('id_planning_stage', $this->id_planning_stage);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
