<?php

/**
 * This is the model base class for the table "budget_previ".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BudgetPrevi".
 *
 * Columns in table "budget_previ" available as properties of the model,
 * followed by relations of table "budget_previ" available as properties of the model.
 *
 * @property integer $id_budget_previ
 * @property integer $id_exercice
 * @property integer $id_budget_chapitre
 * @property string $previsionnel
 * @property string $commentaire
 *
 * @property Exercice $idExercice
 * @property BudgetChapitre $idBudgetChapitre
 */
abstract class BaseBudgetPrevi extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'budget_previ';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BudgetPrevi|BudgetPrevis', $n);
	}

	public static function representingColumn() {
		return 'previsionnel';
	}

	public function rules() {
		return array(
			array('id_exercice, id_budget_chapitre', 'required'),
			array('id_exercice, id_budget_chapitre', 'numerical', 'integerOnly'=>true),
			array('previsionnel', 'length', 'max'=>10),
			array('commentaire', 'safe'),
			array('previsionnel, commentaire', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_budget_previ, id_exercice, id_budget_chapitre, previsionnel, commentaire', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idExercice' => array(self::BELONGS_TO, 'Exercice', 'id_exercice'),
			'idBudgetChapitre' => array(self::BELONGS_TO, 'BudgetChapitre', 'id_budget_chapitre'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_budget_previ' => Yii::t('app', 'Id Budget Previ'),
			'id_exercice' => null,
			'id_budget_chapitre' => null,
			'previsionnel' => Yii::t('app', 'Previsionnel'),
			'commentaire' => Yii::t('app', 'Commentaire'),
			'idExercice' => null,
			'idBudgetChapitre' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_budget_previ', $this->id_budget_previ);
		$criteria->compare('id_exercice', $this->id_exercice);
		$criteria->compare('id_budget_chapitre', $this->id_budget_chapitre);
		$criteria->compare('previsionnel', $this->previsionnel, true);
		$criteria->compare('commentaire', $this->commentaire, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
