<?php

/**
 * This is the model base class for the table "type_piece_ecr".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TypePieceEcr".
 *
 * Columns in table "type_piece_ecr" available as properties of the model,
 * followed by relations of table "type_piece_ecr" available as properties of the model.
 *
 * @property integer $id_type_piece_ecr
 * @property integer $id_type_piece
 * @property integer $ordre
 * @property string $du_compte
 * @property string $au_compte
 * @property string $compte_defaut
 * @property boolean $que_actif
 * @property boolean $est_duplicable
 * @property string $sens
 *
 * @property PieceLigne[] $pieceLignes
 * @property TypePiece $idTypePiece
 */
abstract class BaseTypePieceEcr extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'type_piece_ecr';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TypePieceEcr|TypePieceEcrs', $n);
	}

	public static function representingColumn() {
		return 'du_compte';
	}

	public function rules() {
		return array(
			array('id_type_piece, du_compte, au_compte, compte_defaut', 'required'),
			array('id_type_piece, ordre', 'numerical', 'integerOnly'=>true),
			array('du_compte, au_compte, compte_defaut', 'length', 'max'=>10),
			array('sens', 'length', 'max'=>1),
			array('que_actif, est_duplicable', 'safe'),
			array('ordre, que_actif, est_duplicable, sens', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_type_piece_ecr, id_type_piece, ordre, du_compte, au_compte, compte_defaut, que_actif, est_duplicable, sens', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pieceLignes' => array(self::HAS_MANY, 'PieceLigne', 'id_type_piece_ecr'),
			'idTypePiece' => array(self::BELONGS_TO, 'TypePiece', 'id_type_piece'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_type_piece_ecr' => Yii::t('app', 'Id Type Piece Ecr'),
			'id_type_piece' => null,
			'ordre' => Yii::t('app', 'Ordre'),
			'du_compte' => Yii::t('app', 'Du Compte'),
			'au_compte' => Yii::t('app', 'Au Compte'),
			'compte_defaut' => Yii::t('app', 'Compte Defaut'),
			'que_actif' => Yii::t('app', 'Que Actif'),
			'est_duplicable' => Yii::t('app', 'Est Duplicable'),
			'sens' => Yii::t('app', 'Sens'),
			'pieceLignes' => null,
			'idTypePiece' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_type_piece_ecr', $this->id_type_piece_ecr);
		$criteria->compare('id_type_piece', $this->id_type_piece);
		$criteria->compare('ordre', $this->ordre);
		$criteria->compare('du_compte', $this->du_compte, true);
		$criteria->compare('au_compte', $this->au_compte, true);
		$criteria->compare('compte_defaut', $this->compte_defaut, true);
		$criteria->compare('que_actif', $this->que_actif);
		$criteria->compare('est_duplicable', $this->est_duplicable);
		$criteria->compare('sens', $this->sens, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
