<?php

/**
 * This is the model base class for the table "stat_connexion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StatConnexion".
 *
 * Columns in table "stat_connexion" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id_stat_connexion
 * @property string $client
 * @property string $texte
 * @property string $date_time
 * @property boolean $reussie
 *
 */
abstract class BaseStatConnexion extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'stat_connexion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StatConnexion|StatConnexions', $n);
	}

	public static function representingColumn() {
		return 'client';
	}

	public function rules() {
		return array(
			array('client, texte, date_time', 'required'),
			array('client, texte', 'length', 'max'=>255),
			array('date_time', 'length', 'max'=>6),
			array('reussie', 'safe'),
			array('reussie', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_stat_connexion, client, texte, date_time, reussie', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_stat_connexion' => Yii::t('app', 'Id Stat Connexion'),
			'client' => Yii::t('app', 'Client'),
			'texte' => Yii::t('app', 'Texte'),
			'date_time' => Yii::t('app', 'Date Time'),
			'reussie' => Yii::t('app', 'Reussie'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_stat_connexion', $this->id_stat_connexion, true);
		$criteria->compare('client', $this->client, true);
		$criteria->compare('texte', $this->texte, true);
		$criteria->compare('date_time', $this->date_time, true);
		$criteria->compare('reussie', $this->reussie);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
