<?php

/**
 * This is the model base class for the table "tarif_type_treuillee".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TarifTypeTreuillee".
 *
 * Columns in table "tarif_type_treuillee" available as properties of the model,
 * followed by relations of table "tarif_type_treuillee" available as properties of the model.
 *
 * @property integer $id_tarif_type_date
 * @property string $prix
 * @property integer $id_tarif_tranche
 * @property integer $id_club
 * @property string $max
 * @property string $max_vol
 * @property string $pourcentage
 *
 * @property Club $idClub
 * @property TarifTranche $idTarifTranche
 * @property TarifTypeDate $idTarifTypeDate
 */
abstract class BaseTarifTypeTreuillee extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tarif_type_treuillee';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TarifTypeTreuillee|TarifTypeTreuillees', $n);
	}

	public static function representingColumn() {
		return 'prix';
	}

	public function rules() {
		return array(
			array('id_tarif_type_date', 'required'),
			array('id_tarif_type_date, id_tarif_tranche, id_club', 'numerical', 'integerOnly'=>true),
			array('prix, max, max_vol', 'length', 'max'=>10),
			array('pourcentage', 'length', 'max'=>5),
			array('prix, id_tarif_tranche, id_club, max, max_vol, pourcentage', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tarif_type_date, prix, id_tarif_tranche, id_club, max, max_vol, pourcentage', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idClub' => array(self::BELONGS_TO, 'Club', 'id_club'),
			'idTarifTranche' => array(self::BELONGS_TO, 'TarifTranche', 'id_tarif_tranche'),
			'idTarifTypeDate' => array(self::BELONGS_TO, 'TarifTypeDate', 'id_tarif_type_date'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tarif_type_date' => null,
			'prix' => Yii::t('app', 'Prix'),
			'id_tarif_tranche' => null,
			'id_club' => null,
			'max' => Yii::t('app', 'Max'),
			'max_vol' => Yii::t('app', 'Max Vol'),
			'pourcentage' => Yii::t('app', 'Pourcentage'),
			'idClub' => null,
			'idTarifTranche' => null,
			'idTarifTypeDate' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tarif_type_date', $this->id_tarif_type_date);
		$criteria->compare('prix', $this->prix, true);
		$criteria->compare('id_tarif_tranche', $this->id_tarif_tranche);
		$criteria->compare('id_club', $this->id_club);
		$criteria->compare('max', $this->max, true);
		$criteria->compare('max_vol', $this->max_vol, true);
		$criteria->compare('pourcentage', $this->pourcentage, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
