<?php

/**
 * This is the model base class for the table "inscript_pack_content".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InscriptPackContent".
 *
 * Columns in table "inscript_pack_content" available as properties of the model,
 * followed by relations of table "inscript_pack_content" available as properties of the model.
 *
 * @property integer $id_inscript_pack_content
 * @property integer $id_inscript_pack
 * @property integer $pack_ordre
 * @property string $libelle
 * @property boolean $complement
 * @property boolean $coche
 * @property string $categorie
 * @property string $code
 *
 * @property InscriptPack $idInscriptPack
 */
abstract class BaseInscriptPackContent extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inscript_pack_content';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InscriptPackContent|InscriptPackContents', $n);
	}

	public static function representingColumn() {
		return 'categorie';
	}

	public function rules() {
		return array(
			array('id_inscript_pack, pack_ordre', 'required'),
			array('id_inscript_pack, pack_ordre', 'numerical', 'integerOnly'=>true),
			array('libelle', 'length', 'max'=>255),
			array('categorie, code', 'length', 'max'=>15),
			array('complement, coche', 'safe'),
			array('libelle, complement, coche, categorie, code', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_inscript_pack_content, id_inscript_pack, pack_ordre, libelle, complement, coche, categorie, code', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idInscriptPack' => array(self::BELONGS_TO, 'InscriptPack', 'id_inscript_pack'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_inscript_pack_content' => Yii::t('app', 'Id Inscript Pack Content'),
			'id_inscript_pack' => null,
			'pack_ordre' => Yii::t('app', 'Pack Ordre'),
			'libelle' => Yii::t('app', 'Libelle'),
			'complement' => Yii::t('app', 'Complement'),
			'coche' => Yii::t('app', 'Coche'),
			'categorie' => Yii::t('app', 'Categorie'),
			'code' => Yii::t('app', 'Code'),
			'idInscriptPack' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_inscript_pack_content', $this->id_inscript_pack_content);
		$criteria->compare('id_inscript_pack', $this->id_inscript_pack);
		$criteria->compare('pack_ordre', $this->pack_ordre);
		$criteria->compare('libelle', $this->libelle, true);
		$criteria->compare('complement', $this->complement);
		$criteria->compare('coche', $this->coche);
		$criteria->compare('categorie', $this->categorie, true);
		$criteria->compare('code', $this->code, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
