<?php

/**
 * This is the model base class for the table "grille".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Grille".
 *
 * Columns in table "grille" available as properties of the model,
 * followed by relations of table "grille" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_aeronef
 * @property integer $id_pilote
 * @property integer $id_ligne
 * @property string $mode_lancement
 *
 * @property Aeronef $idAeronef
 * @property Pilote $idPilote
 * @property Ligne $idLigne
 * @property GrilleJour[] $grilleJours
 */
abstract class BaseGrille extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'grille';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Grille|Grilles', $n);
	}

	public static function representingColumn() {
		return 'mode_lancement';
	}

	public function rules() {
		return array(
			array('id_aeronef, id_pilote, id_ligne', 'required'),
			array('id_aeronef, id_pilote, id_ligne', 'numerical', 'integerOnly'=>true),
			array('mode_lancement', 'length', 'max'=>1),
			array('mode_lancement', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_aeronef, id_pilote, id_ligne, mode_lancement', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
			'idPilote' => array(self::BELONGS_TO, 'Pilote', 'id_pilote'),
			'idLigne' => array(self::BELONGS_TO, 'Ligne', 'id_ligne'),
			'grilleJours' => array(self::HAS_MANY, 'GrilleJour', 'id_grille'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_aeronef' => null,
			'id_pilote' => null,
			'id_ligne' => null,
			'mode_lancement' => Yii::t('app', 'Mode Lancement'),
			'idAeronef' => null,
			'idPilote' => null,
			'idLigne' => null,
			'grilleJours' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('id_pilote', $this->id_pilote);
		$criteria->compare('id_ligne', $this->id_ligne);
		$criteria->compare('mode_lancement', $this->mode_lancement, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
