<?php

/**
 * This is the model base class for the table "cheque_recu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ChequeRecu".
 *
 * Columns in table "cheque_recu" available as properties of the model,
 * followed by relations of table "cheque_recu" available as properties of the model.
 *
 * @property integer $id_cheque
 * @property integer $id_piece_ligne
 * @property integer $numero
 * @property integer $id_banque_emettrice
 * @property integer $id_remise
 *
 * @property PieceLigne $idPieceLigne
 * @property RemiseBanque $idRemise
 * @property BanqueEmettrice $idBanqueEmettrice
 */
abstract class BaseChequeRecu extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cheque_recu';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ChequeRecu|ChequeRecus', $n);
	}

	public static function representingColumn() {
		return 'id_cheque';
	}

	public function rules() {
		return array(
			array('id_piece_ligne, numero, id_banque_emettrice', 'required'),
			array('id_piece_ligne, numero, id_banque_emettrice, id_remise', 'numerical', 'integerOnly'=>true),
			array('id_remise', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_cheque, id_piece_ligne, numero, id_banque_emettrice, id_remise', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPieceLigne' => array(self::BELONGS_TO, 'PieceLigne', 'id_piece_ligne'),
			'idRemise' => array(self::BELONGS_TO, 'RemiseBanque', 'id_remise'),
			'idBanqueEmettrice' => array(self::BELONGS_TO, 'BanqueEmettrice', 'id_banque_emettrice'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_cheque' => Yii::t('app', 'Id Cheque'),
			'id_piece_ligne' => null,
			'numero' => Yii::t('app', 'Numero'),
			'id_banque_emettrice' => null,
			'id_remise' => null,
			'idPieceLigne' => null,
			'idRemise' => null,
			'idBanqueEmettrice' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_cheque', $this->id_cheque);
		$criteria->compare('id_piece_ligne', $this->id_piece_ligne);
		$criteria->compare('numero', $this->numero);
		$criteria->compare('id_banque_emettrice', $this->id_banque_emettrice);
		$criteria->compare('id_remise', $this->id_remise);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
