<?php

/**
 * This is the model base class for the table "chemise".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Chemise".
 *
 * Columns in table "chemise" available as properties of the model,
 * followed by relations of table "chemise" available as properties of the model.
 *
 * @property integer $id_chemise
 * @property string $libelle
 * @property string $recherche
 * @property string $texte
 * @property string $date_creation
 * @property integer $id_utilisateur_creation
 * @property string $date_modification
 * @property integer $id_utilisateur_modification
 *
 * @property Piece[] $pieces
 * @property LienChemise[] $lienChemises
 * @property Utilisateur $idUtilisateurCreation
 * @property Utilisateur $idUtilisateurModification
 * @property LienFeuille[] $lienFeuilles
 * @property Rapprochement[] $rapprochements
 */
abstract class BaseChemise extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'chemise';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Chemise|Chemises', $n);
	}

	public static function representingColumn() {
		return 'date_creation';
	}

	public function rules() {
		return array(
			array('date_creation, date_modification', 'required'),
			array('libelle, recherche', 'length', 'max'=>120),
			array('texte', 'safe'),
			array('libelle, recherche, texte', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_chemise, libelle, recherche, texte, date_creation, id_utilisateur_creation, date_modification, id_utilisateur_modification', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pieces' => array(self::HAS_MANY, 'Piece', 'id_chemise'),
			'lienChemises' => array(self::HAS_MANY, 'LienChemise', 'id_chemise'),
			'idUtilisateurCreation' => array(self::BELONGS_TO, 'Utilisateur', 'id_utilisateur_creation'),
			'idUtilisateurModification' => array(self::BELONGS_TO, 'Utilisateur', 'id_utilisateur_modification'),
			'lienFeuilles' => array(self::HAS_MANY, 'LienFeuille', 'id_chemise'),
			'rapprochements' => array(self::HAS_MANY, 'Rapprochement', 'id_chemise'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_chemise' => Yii::t('app', 'Id Chemise'),
			'libelle' => Yii::t('app', 'Libelle'),
			'recherche' => Yii::t('app', 'Recherche'),
			'texte' => Yii::t('app', 'Texte'),
			'date_creation' => Yii::t('app', 'Date Creation'),
			'id_utilisateur_creation' => null,
			'date_modification' => Yii::t('app', 'Date Modification'),
			'id_utilisateur_modification' => null,
			'pieces' => null,
			'lienChemises' => null,
			'idUtilisateurCreation' => null,
			'idUtilisateurModification' => null,
			'lienFeuilles' => null,
			'rapprochements' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_chemise', $this->id_chemise);
		$criteria->compare('libelle', $this->libelle, true);
		$criteria->compare('recherche', $this->recherche, true);
		$criteria->compare('texte', $this->texte, true);
		$criteria->compare('date_creation', $this->date_creation, true);
		$criteria->compare('id_utilisateur_creation', $this->id_utilisateur_creation);
		$criteria->compare('date_modification', $this->date_modification, true);
		$criteria->compare('id_utilisateur_modification', $this->id_utilisateur_modification);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
