<?php

/**
 * This is the model base class for the table "budget_valeur".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BudgetValeur".
 *
 * Columns in table "budget_valeur" available as properties of the model,
 * followed by relations of table "budget_valeur" available as properties of the model.
 *
 * @property integer $id_budget_valeur
 * @property integer $id_piece
 * @property integer $id_budget_chapitre
 * @property string $realise
 * @property string $date_piece
 *
 * @property Piece $idPiece
 * @property BudgetChapitre $idBudgetChapitre
 */
abstract class BaseBudgetValeur extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'budget_valeur';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BudgetValeur|BudgetValeurs', $n);
	}

	public static function representingColumn() {
		return 'realise';
	}

	public function rules() {
		return array(
			array('id_piece, id_budget_chapitre, date_piece', 'required'),
			array('id_piece, id_budget_chapitre', 'numerical', 'integerOnly'=>true),
			array('realise', 'length', 'max'=>10),
			array('realise', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_budget_valeur, id_piece, id_budget_chapitre, realise, date_piece', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPiece' => array(self::BELONGS_TO, 'Piece', 'id_piece'),
			'idBudgetChapitre' => array(self::BELONGS_TO, 'BudgetChapitre', 'id_budget_chapitre'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_budget_valeur' => Yii::t('app', 'Id Budget Valeur'),
			'id_piece' => null,
			'id_budget_chapitre' => null,
			'realise' => Yii::t('app', 'Realise'),
			'date_piece' => Yii::t('app', 'Date Piece'),
			'idPiece' => null,
			'idBudgetChapitre' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_budget_valeur', $this->id_budget_valeur);
		$criteria->compare('id_piece', $this->id_piece);
		$criteria->compare('id_budget_chapitre', $this->id_budget_chapitre);
		$criteria->compare('realise', $this->realise, true);
		$criteria->compare('date_piece', $this->date_piece, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
