<?php

/**
 * This is the model base class for the table "stat_tempo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StatTempo".
 *
 * Columns in table "stat_tempo" available as properties of the model,
 * followed by relations of table "stat_tempo" available as properties of the model.
 *
 * @property integer $id_utilisateur
 * @property integer $id_annu
 * @property integer $annee
 * @property string $tps_cdt_bord
 * @property string $tps_passager
 * @property string $tps_instructeur
 * @property string $tps_eleve
 * @property string $tps_moteur_cdt_bord
 * @property string $tps_moteur_passager
 * @property string $tps_moteur_instructeur
 * @property string $tps_moteur_eleve
 * @property integer $nb_treuillee_cdt_bord
 * @property integer $nb_treuillee_passager
 * @property integer $nb_treuillee_instructeur
 * @property integer $nb_treuillee_eleve
 * @property integer $nb_remorque_cdt_bord
 * @property integer $nb_remorque_passager
 * @property integer $nb_remorque_instructeur
 * @property integer $nb_remorque_eleve
 * @property integer $nb_vi_club
 * @property integer $nb_vi_perso
 * @property integer $nb_treuillee_treuilleur
 * @property integer $nb_remorque_remorqueur
 * @property string $date_theorique
 * @property string $date_lache
 * @property string $date_brevet
 * @property string $date_campagne
 * @property string $date_emport_passager
 * @property string $tps_remorque_remorqueur
 *
 * @property Annuaire $idAnnu
 */
abstract class BaseStatTempo extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'stat_tempo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StatTempo|StatTempos', $n);
	}

	public static function representingColumn() {
		return 'date_theorique';
	}

	public function rules() {
		return array(
			array('id_utilisateur, id_annu, annee', 'required'),
			array('id_utilisateur, id_annu, annee, nb_treuillee_cdt_bord, nb_treuillee_passager, nb_treuillee_instructeur, nb_treuillee_eleve, nb_remorque_cdt_bord, nb_remorque_passager, nb_remorque_instructeur, nb_remorque_eleve, nb_vi_club, nb_vi_perso, nb_treuillee_treuilleur, nb_remorque_remorqueur', 'numerical', 'integerOnly'=>true),
			array('tps_cdt_bord, tps_passager, tps_instructeur, tps_eleve, tps_moteur_cdt_bord, tps_moteur_passager, tps_moteur_instructeur, tps_moteur_eleve, date_theorique, date_lache, date_brevet, date_campagne, date_emport_passager, tps_remorque_remorqueur', 'safe'),
			array('tps_cdt_bord, tps_passager, tps_instructeur, tps_eleve, tps_moteur_cdt_bord, tps_moteur_passager, tps_moteur_instructeur, tps_moteur_eleve, nb_treuillee_cdt_bord, nb_treuillee_passager, nb_treuillee_instructeur, nb_treuillee_eleve, nb_remorque_cdt_bord, nb_remorque_passager, nb_remorque_instructeur, nb_remorque_eleve, nb_vi_club, nb_vi_perso, nb_treuillee_treuilleur, nb_remorque_remorqueur, date_theorique, date_lache, date_brevet, date_campagne, date_emport_passager, tps_remorque_remorqueur', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_utilisateur, id_annu, annee, tps_cdt_bord, tps_passager, tps_instructeur, tps_eleve, tps_moteur_cdt_bord, tps_moteur_passager, tps_moteur_instructeur, tps_moteur_eleve, nb_treuillee_cdt_bord, nb_treuillee_passager, nb_treuillee_instructeur, nb_treuillee_eleve, nb_remorque_cdt_bord, nb_remorque_passager, nb_remorque_instructeur, nb_remorque_eleve, nb_vi_club, nb_vi_perso, nb_treuillee_treuilleur, nb_remorque_remorqueur, date_theorique, date_lache, date_brevet, date_campagne, date_emport_passager, tps_remorque_remorqueur', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAnnu' => array(self::BELONGS_TO, 'Annuaire', 'id_annu'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_utilisateur' => Yii::t('app', 'Id Utilisateur'),
			'id_annu' => null,
			'annee' => Yii::t('app', 'Annee'),
			'tps_cdt_bord' => Yii::t('app', 'Tps Cdt Bord'),
			'tps_passager' => Yii::t('app', 'Tps Passager'),
			'tps_instructeur' => Yii::t('app', 'Tps Instructeur'),
			'tps_eleve' => Yii::t('app', 'Tps Eleve'),
			'tps_moteur_cdt_bord' => Yii::t('app', 'Tps Moteur Cdt Bord'),
			'tps_moteur_passager' => Yii::t('app', 'Tps Moteur Passager'),
			'tps_moteur_instructeur' => Yii::t('app', 'Tps Moteur Instructeur'),
			'tps_moteur_eleve' => Yii::t('app', 'Tps Moteur Eleve'),
			'nb_treuillee_cdt_bord' => Yii::t('app', 'Nb Treuillee Cdt Bord'),
			'nb_treuillee_passager' => Yii::t('app', 'Nb Treuillee Passager'),
			'nb_treuillee_instructeur' => Yii::t('app', 'Nb Treuillee Instructeur'),
			'nb_treuillee_eleve' => Yii::t('app', 'Nb Treuillee Eleve'),
			'nb_remorque_cdt_bord' => Yii::t('app', 'Nb Remorque Cdt Bord'),
			'nb_remorque_passager' => Yii::t('app', 'Nb Remorque Passager'),
			'nb_remorque_instructeur' => Yii::t('app', 'Nb Remorque Instructeur'),
			'nb_remorque_eleve' => Yii::t('app', 'Nb Remorque Eleve'),
			'nb_vi_club' => Yii::t('app', 'Nb Vi Club'),
			'nb_vi_perso' => Yii::t('app', 'Nb Vi Perso'),
			'nb_treuillee_treuilleur' => Yii::t('app', 'Nb Treuillee Treuilleur'),
			'nb_remorque_remorqueur' => Yii::t('app', 'Nb Remorque Remorqueur'),
			'date_theorique' => Yii::t('app', 'Date Theorique'),
			'date_lache' => Yii::t('app', 'Date Lache'),
			'date_brevet' => Yii::t('app', 'Date Brevet'),
			'date_campagne' => Yii::t('app', 'Date Campagne'),
			'date_emport_passager' => Yii::t('app', 'Date Emport Passager'),
			'tps_remorque_remorqueur' => Yii::t('app', 'Tps Remorque Remorqueur'),
			'idAnnu' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_utilisateur', $this->id_utilisateur);
		$criteria->compare('id_annu', $this->id_annu);
		$criteria->compare('annee', $this->annee);
		$criteria->compare('tps_cdt_bord', $this->tps_cdt_bord, true);
		$criteria->compare('tps_passager', $this->tps_passager, true);
		$criteria->compare('tps_instructeur', $this->tps_instructeur, true);
		$criteria->compare('tps_eleve', $this->tps_eleve, true);
		$criteria->compare('tps_moteur_cdt_bord', $this->tps_moteur_cdt_bord, true);
		$criteria->compare('tps_moteur_passager', $this->tps_moteur_passager, true);
		$criteria->compare('tps_moteur_instructeur', $this->tps_moteur_instructeur, true);
		$criteria->compare('tps_moteur_eleve', $this->tps_moteur_eleve, true);
		$criteria->compare('nb_treuillee_cdt_bord', $this->nb_treuillee_cdt_bord);
		$criteria->compare('nb_treuillee_passager', $this->nb_treuillee_passager);
		$criteria->compare('nb_treuillee_instructeur', $this->nb_treuillee_instructeur);
		$criteria->compare('nb_treuillee_eleve', $this->nb_treuillee_eleve);
		$criteria->compare('nb_remorque_cdt_bord', $this->nb_remorque_cdt_bord);
		$criteria->compare('nb_remorque_passager', $this->nb_remorque_passager);
		$criteria->compare('nb_remorque_instructeur', $this->nb_remorque_instructeur);
		$criteria->compare('nb_remorque_eleve', $this->nb_remorque_eleve);
		$criteria->compare('nb_vi_club', $this->nb_vi_club);
		$criteria->compare('nb_vi_perso', $this->nb_vi_perso);
		$criteria->compare('nb_treuillee_treuilleur', $this->nb_treuillee_treuilleur);
		$criteria->compare('nb_remorque_remorqueur', $this->nb_remorque_remorqueur);
		$criteria->compare('date_theorique', $this->date_theorique, true);
		$criteria->compare('date_lache', $this->date_lache, true);
		$criteria->compare('date_brevet', $this->date_brevet, true);
		$criteria->compare('date_campagne', $this->date_campagne, true);
		$criteria->compare('date_emport_passager', $this->date_emport_passager, true);
		$criteria->compare('tps_remorque_remorqueur', $this->tps_remorque_remorqueur, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
