<?php

/**
 * This is the model base class for the table "piece_ligne".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PieceLigne".
 *
 * Columns in table "piece_ligne" available as properties of the model,
 * followed by relations of table "piece_ligne" available as properties of the model.
 *
 * @property integer $id_piece_ligne
 * @property integer $id_piece
 * @property integer $ordre
 * @property integer $id_compte
 * @property string $debit
 * @property string $credit
 * @property string $lettrage
 * @property integer $id_rapprochement
 * @property integer $id_type_piece_ecr
 * @property string $date_piece
 *
 * @property Piece $idPiece
 * @property Compte $idCompte
 * @property Rapprochement $idRapprochement
 * @property TypePieceEcr $idTypePieceEcr
 * @property ChequeRecu[] $chequeRecus
 * @property ChequeEmis[] $chequeEmises
 */
abstract class BasePieceLigne extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'piece_ligne';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PieceLigne|PieceLignes', $n);
	}

	public static function representingColumn() {
		return 'debit';
	}

	public function rules() {
		return array(
			array('id_piece, id_compte, id_type_piece_ecr, date_piece', 'required'),
			array('id_piece, ordre, id_compte, id_rapprochement, id_type_piece_ecr', 'numerical', 'integerOnly'=>true),
			array('debit, credit', 'length', 'max'=>10),
			array('lettrage', 'length', 'max'=>4),
			array('ordre, debit, credit, lettrage, id_rapprochement', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_piece_ligne, id_piece, ordre, id_compte, debit, credit, lettrage, id_rapprochement, id_type_piece_ecr, date_piece', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPiece' => array(self::BELONGS_TO, 'Piece', 'id_piece'),
			'idCompte' => array(self::BELONGS_TO, 'Compte', 'id_compte'),
			'idRapprochement' => array(self::BELONGS_TO, 'Rapprochement', 'id_rapprochement'),
			'idTypePieceEcr' => array(self::BELONGS_TO, 'TypePieceEcr', 'id_type_piece_ecr'),
			'chequeRecus' => array(self::HAS_MANY, 'ChequeRecu', 'id_piece_ligne'),
			'chequeEmises' => array(self::HAS_MANY, 'ChequeEmis', 'id_piece_ligne'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_piece_ligne' => Yii::t('app', 'Id Piece Ligne'),
			'id_piece' => null,
			'ordre' => Yii::t('app', 'Ordre'),
			'id_compte' => null,
			'debit' => Yii::t('app', 'Debit'),
			'credit' => Yii::t('app', 'Credit'),
			'lettrage' => Yii::t('app', 'Lettrage'),
			'id_rapprochement' => null,
			'id_type_piece_ecr' => null,
			'date_piece' => Yii::t('app', 'Date Piece'),
			'idPiece' => null,
			'idCompte' => null,
			'idRapprochement' => null,
			'idTypePieceEcr' => null,
			'chequeRecus' => null,
			'chequeEmises' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_piece_ligne', $this->id_piece_ligne);
		$criteria->compare('id_piece', $this->id_piece);
		$criteria->compare('ordre', $this->ordre);
		$criteria->compare('id_compte', $this->id_compte);
		$criteria->compare('debit', $this->debit, true);
		$criteria->compare('credit', $this->credit, true);
		$criteria->compare('lettrage', $this->lettrage, true);
		$criteria->compare('id_rapprochement', $this->id_rapprochement);
		$criteria->compare('id_type_piece_ecr', $this->id_type_piece_ecr);
		$criteria->compare('date_piece', $this->date_piece, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
