<?php

/**
 * This is the model base class for the table "classeur".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Classeur".
 *
 * Columns in table "classeur" available as properties of the model,
 * followed by relations of table "classeur" available as properties of the model.
 *
 * @property integer $id_classeur
 * @property string $libelle
 * @property string $recherche
 * @property string $date_creation
 * @property integer $id_utilisateur_creation
 * @property string $date_modification
 * @property integer $id_utilisateur_modification
 * @property integer $id_pere
 *
 * @property Compte[] $comptes
 * @property LienChemise[] $lienChemises
 * @property Utilisateur $idUtilisateurModification
 * @property Classeur $idPere
 * @property Classeur[] $classeurs
 * @property Utilisateur $idUtilisateurCreation
 * @property Annuaire[] $annuaires
 */
abstract class BaseClasseur extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'classeur';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Classeur|Classeurs', $n);
	}

	public static function representingColumn() {
		return 'libelle';
	}

	public function rules() {
		return array(
			array('libelle, recherche, date_creation, date_modification', 'required'),
			array('id_pere', 'numerical', 'integerOnly'=>true),
			array('libelle, recherche', 'length', 'max'=>120),
			array('id_pere', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_classeur, libelle, recherche, date_creation, id_utilisateur_creation, date_modification, id_utilisateur_modification, id_pere', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'comptes' => array(self::HAS_MANY, 'Compte', 'id_classeur'),
			'lienChemises' => array(self::HAS_MANY, 'LienChemise', 'id_classeur'),
			'idUtilisateurModification' => array(self::BELONGS_TO, 'Utilisateur', 'id_utilisateur_modification'),
			'idPere' => array(self::BELONGS_TO, 'Classeur', 'id_pere'),
			'classeurs' => array(self::HAS_MANY, 'Classeur', 'id_pere'),
			'idUtilisateurCreation' => array(self::BELONGS_TO, 'Utilisateur', 'id_utilisateur_creation'),
			'annuaires' => array(self::HAS_MANY, 'Annuaire', 'id_classeur'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_classeur' => Yii::t('app', 'Id Classeur'),
			'libelle' => Yii::t('app', 'Libelle'),
			'recherche' => Yii::t('app', 'Recherche'),
			'date_creation' => Yii::t('app', 'Date Creation'),
			'id_utilisateur_creation' => null,
			'date_modification' => Yii::t('app', 'Date Modification'),
			'id_utilisateur_modification' => null,
			'id_pere' => null,
			'comptes' => null,
			'lienChemises' => null,
			'idUtilisateurModification' => null,
			'idPere' => null,
			'classeurs' => null,
			'idUtilisateurCreation' => null,
			'annuaires' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_classeur', $this->id_classeur);
		$criteria->compare('libelle', $this->libelle, true);
		$criteria->compare('recherche', $this->recherche, true);
		$criteria->compare('date_creation', $this->date_creation, true);
		$criteria->compare('id_utilisateur_creation', $this->id_utilisateur_creation);
		$criteria->compare('date_modification', $this->date_modification, true);
		$criteria->compare('id_utilisateur_modification', $this->id_utilisateur_modification);
		$criteria->compare('id_pere', $this->id_pere);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
