<?php

/**
 * This is the model base class for the table "remorque".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Remorque".
 *
 * Columns in table "remorque" available as properties of the model,
 * followed by relations of table "remorque" available as properties of the model.
 *
 * @property integer $id_remorque
 * @property integer $ordre
 * @property string $code
 * @property string $libelle
 * @property boolean $defaut
 * @property boolean $actif
 * @property boolean $saisie_temps
 * @property string $temps
 *
 * @property Concours[] $concours
 * @property Vol[] $vols
 * @property TarifTypeDate[] $tarifTypeDates
 * @property RemorqueurTemps[] $remorqueurTemps
 */
abstract class BaseRemorque extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'remorque';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Remorque|Remorques', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('ordre, code', 'required'),
			array('ordre', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>10),
			array('libelle', 'length', 'max'=>255),
			array('defaut, actif, saisie_temps, temps', 'safe'),
			array('libelle, defaut, actif, saisie_temps, temps', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_remorque, ordre, code, libelle, defaut, actif, saisie_temps, temps', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'concours' => array(self::HAS_MANY, 'Concours', 'id_remorque'),
			'vols' => array(self::HAS_MANY, 'Vol', 'id_remorque'),
			'tarifTypeDates' => array(self::MANY_MANY, 'TarifTypeDate', 'tarif_type_remorque(id_remorque, id_tarif_type_date)'),
			'remorqueurTemps' => array(self::HAS_MANY, 'RemorqueurTemps', 'id_remorque'),
		);
	}

	public function pivotModels() {
		return array(
			'tarifTypeDates' => 'TarifTypeRemorque',
		);
	}

	public function attributeLabels() {
		return array(
			'id_remorque' => Yii::t('app', 'Id Remorque'),
			'ordre' => Yii::t('app', 'Ordre'),
			'code' => Yii::t('app', 'Code'),
			'libelle' => Yii::t('app', 'Libelle'),
			'defaut' => Yii::t('app', 'Defaut'),
			'actif' => Yii::t('app', 'Actif'),
			'saisie_temps' => Yii::t('app', 'Saisie Temps'),
			'temps' => Yii::t('app', 'Temps'),
			'concours' => null,
			'vols' => null,
			'tarifTypeDates' => null,
			'remorqueurTemps' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_remorque', $this->id_remorque);
		$criteria->compare('ordre', $this->ordre);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('libelle', $this->libelle, true);
		$criteria->compare('defaut', $this->defaut);
		$criteria->compare('actif', $this->actif);
		$criteria->compare('saisie_temps', $this->saisie_temps);
		$criteria->compare('temps', $this->temps, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
