<?php

/**
 * This is the model base class for the table "pays".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Pays".
 *
 * Columns in table "pays" available as properties of the model,
 * followed by relations of table "pays" available as properties of the model.
 *
 * @property string $pays
 * @property integer $id_pays
 * @property string $code_pays
 *
 * @property Annuaire[] $annuaires
 * @property DemandeStage[] $demandeStages
 */
abstract class BasePays extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pays';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Pays|Pays', $n);
	}

	public static function representingColumn() {
		return 'pays';
	}

	public function rules() {
		return array(
			array('pays', 'required'),
			array('id_pays', 'numerical', 'integerOnly'=>true),
			array('pays', 'length', 'max'=>60),
			array('code_pays', 'length', 'max'=>2),
			array('id_pays, code_pays', 'default', 'setOnEmpty' => true, 'value' => null),
			array('pays, id_pays, code_pays', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'annuaires' => array(self::HAS_MANY, 'Annuaire', 'pays'),
			'demandeStages' => array(self::HAS_MANY, 'DemandeStage', 'pays'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'pays' => Yii::t('app', 'Pays'),
			'id_pays' => Yii::t('app', 'Id Pays'),
			'code_pays' => Yii::t('app', 'Code Pays'),
			'annuaires' => null,
			'demandeStages' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('pays', $this->pays, true);
		$criteria->compare('id_pays', $this->id_pays);
		$criteria->compare('code_pays', $this->code_pays, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
