<?php

/**
 * This is the model base class for the table "plan_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PlanLog".
 *
 * Columns in table "plan_log" available as properties of the model,
 * followed by relations of table "plan_log" available as properties of the model.
 *
 * @property integer $id_plan_log
 * @property integer $id_planning
 * @property integer $saison
 * @property string $date_log
 * @property string $texte_log
 *
 * @property Planning $idPlanning
 */
abstract class BasePlanLog extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'plan_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PlanLog|PlanLogs', $n);
	}

	public static function representingColumn() {
		return 'date_log';
	}

	public function rules() {
		return array(
			array('id_planning, saison, date_log, texte_log', 'required'),
			array('id_planning, saison', 'numerical', 'integerOnly'=>true),
			array('id_plan_log, id_planning, saison, date_log, texte_log', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPlanning' => array(self::BELONGS_TO, 'Planning', 'id_planning'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_plan_log' => Yii::t('app', 'Id Plan Log'),
			'id_planning' => null,
			'saison' => Yii::t('app', 'Saison'),
			'date_log' => Yii::t('app', 'Date Log'),
			'texte_log' => Yii::t('app', 'Texte Log'),
			'idPlanning' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_plan_log', $this->id_plan_log);
		$criteria->compare('id_planning', $this->id_planning);
		$criteria->compare('saison', $this->saison);
		$criteria->compare('date_log', $this->date_log, true);
		$criteria->compare('texte_log', $this->texte_log, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
