<?php

/**
 * This is the model base class for the table "utilisateur".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Utilisateur".
 *
 * Columns in table "utilisateur" available as properties of the model,
 * followed by relations of table "utilisateur" available as properties of the model.
 *
 * @property integer $id_utilisateur
 * @property integer $id_annu
 * @property string $date_sortie
 * @property boolean $administrateur
 * @property boolean $administrateur_ged
 * @property boolean $adm_membre
 * @property boolean $adm_compta
 * @property string $courriel_from
 * @property string $code_modele
 * @property string $courriel_cc
 * @property string $courriel_bcc
 *
 * @property EvenementPilote[] $evenementPilotes
 * @property EvenementPilote[] $evenementPilotes1
 * @property Piece[] $pieces
 * @property Piece[] $pieces1
 * @property Chemise[] $chemises
 * @property Chemise[] $chemises1
 * @property MenuDroit[] $menuDroits
 * @property Classeur[] $classeurs
 * @property Classeur[] $classeurs1
 * @property Annuaire $idAnnu
 * @property Vol[] $vols
 * @property Vol[] $vols1
 * @property Courriel[] $courriels
 */
abstract class BaseUtilisateur extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'utilisateur';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Utilisateur|Utilisateurs', $n);
	}

	public static function representingColumn() {
		return 'date_sortie';
	}

	public function rules() {
		return array(
			array('id_annu', 'required'),
			array('id_annu', 'numerical', 'integerOnly'=>true),
			array('courriel_from', 'length', 'max'=>60),
			array('code_modele', 'length', 'max'=>10),
			array('courriel_cc, courriel_bcc', 'length', 'max'=>500),
			array('date_sortie, administrateur, administrateur_ged, adm_membre, adm_compta', 'safe'),
			array('date_sortie, administrateur, administrateur_ged, adm_membre, adm_compta, courriel_from, code_modele, courriel_cc, courriel_bcc', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_utilisateur, id_annu, date_sortie, administrateur, administrateur_ged, adm_membre, adm_compta, courriel_from, code_modele, courriel_cc, courriel_bcc', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'evenementPilotes' => array(self::HAS_MANY, 'EvenementPilote', 'id_utilisateur_creation'),
			'evenementPilotes1' => array(self::HAS_MANY, 'EvenementPilote', 'id_utilisateur_modification'),
			'pieces' => array(self::HAS_MANY, 'Piece', 'id_utilisateur_creation'),
			'pieces1' => array(self::HAS_MANY, 'Piece', 'id_utilisateur_modification'),
			'chemises' => array(self::HAS_MANY, 'Chemise', 'id_utilisateur_creation'),
			'chemises1' => array(self::HAS_MANY, 'Chemise', 'id_utilisateur_modification'),
			'menuDroits' => array(self::HAS_MANY, 'MenuDroit', 'id_utilisateur'),
			'classeurs' => array(self::HAS_MANY, 'Classeur', 'id_utilisateur_modification'),
			'classeurs1' => array(self::HAS_MANY, 'Classeur', 'id_utilisateur_creation'),
			'idAnnu' => array(self::BELONGS_TO, 'Annuaire', 'id_annu'),
			'vols' => array(self::HAS_MANY, 'Vol', 'id_utilisateur_creation'),
			'vols1' => array(self::HAS_MANY, 'Vol', 'id_utilisateur_modification'),
			'courriels' => array(self::HAS_MANY, 'Courriel', 'id_utilisateur'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_utilisateur' => Yii::t('app', 'Id Utilisateur'),
			'id_annu' => null,
			'date_sortie' => Yii::t('app', 'Date Sortie'),
			'administrateur' => Yii::t('app', 'Administrateur'),
			'administrateur_ged' => Yii::t('app', 'Administrateur Ged'),
			'adm_membre' => Yii::t('app', 'Adm Membre'),
			'adm_compta' => Yii::t('app', 'Adm Compta'),
			'courriel_from' => Yii::t('app', 'Courriel From'),
			'code_modele' => Yii::t('app', 'Code Modele'),
			'courriel_cc' => Yii::t('app', 'Courriel Cc'),
			'courriel_bcc' => Yii::t('app', 'Courriel Bcc'),
			'evenementPilotes' => null,
			'evenementPilotes1' => null,
			'pieces' => null,
			'pieces1' => null,
			'chemises' => null,
			'chemises1' => null,
			'menuDroits' => null,
			'classeurs' => null,
			'classeurs1' => null,
			'idAnnu' => null,
			'vols' => null,
			'vols1' => null,
			'courriels' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_utilisateur', $this->id_utilisateur);
		$criteria->compare('id_annu', $this->id_annu);
		$criteria->compare('date_sortie', $this->date_sortie, true);
		$criteria->compare('administrateur', $this->administrateur);
		$criteria->compare('administrateur_ged', $this->administrateur_ged);
		$criteria->compare('adm_membre', $this->adm_membre);
		$criteria->compare('adm_compta', $this->adm_compta);
		$criteria->compare('courriel_from', $this->courriel_from, true);
		$criteria->compare('code_modele', $this->code_modele, true);
		$criteria->compare('courriel_cc', $this->courriel_cc, true);
		$criteria->compare('courriel_bcc', $this->courriel_bcc, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
