<?php

/**
 * This is the model base class for the table "remorqueur_activite".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RemorqueurActivite".
 *
 * Columns in table "remorqueur_activite" available as properties of the model,
 * followed by relations of table "remorqueur_activite" available as properties of the model.
 *
 * @property integer $id_remorqueur_activite
 * @property integer $id_aeronef
 * @property string $date_activite
 * @property integer $heures_vol
 * @property integer $heures_moteur
 * @property integer $crochet
 *
 * @property Aeronef $idAeronef
 */
abstract class BaseRemorqueurActivite extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'remorqueur_activite';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RemorqueurActivite|RemorqueurActivites', $n);
	}

	public static function representingColumn() {
		return 'date_activite';
	}

	public function rules() {
		return array(
			array('id_aeronef, date_activite', 'required'),
			array('id_aeronef, heures_vol, heures_moteur, crochet', 'numerical', 'integerOnly'=>true),
			array('heures_vol, heures_moteur, crochet', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_remorqueur_activite, id_aeronef, date_activite, heures_vol, heures_moteur, crochet', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_remorqueur_activite' => Yii::t('app', 'Id Remorqueur Activite'),
			'id_aeronef' => null,
			'date_activite' => Yii::t('app', 'Date Activite'),
			'heures_vol' => Yii::t('app', 'Heures Vol'),
			'heures_moteur' => Yii::t('app', 'Heures Moteur'),
			'crochet' => Yii::t('app', 'Crochet'),
			'idAeronef' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_remorqueur_activite', $this->id_remorqueur_activite);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('date_activite', $this->date_activite, true);
		$criteria->compare('heures_vol', $this->heures_vol);
		$criteria->compare('heures_moteur', $this->heures_moteur);
		$criteria->compare('crochet', $this->crochet);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
