<?php

/**
 * This is the model base class for the table "stage".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Stage".
 *
 * Columns in table "stage" available as properties of the model,
 * followed by relations of table "stage" available as properties of the model.
 *
 * @property integer $id_stage
 * @property integer $id_pilote
 * @property integer $id_aeronef
 * @property integer $id_hebergement
 * @property string $date_arrivee
 * @property string $date_depart
 * @property string $commentaire
 * @property string $date_time_demande
 * @property boolean $licence_assurance_ffvv
 * @property integer $id_planning_stage
 *
 * @property Pilote $idPilote
 * @property Aeronef $idAeronef
 * @property Hebergement $idHebergement
 * @property PlanningStage $idPlanningStage
 */
abstract class BaseStage extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'stage';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Stage|Stages', $n);
	}

	public static function representingColumn() {
		return 'date_arrivee';
	}

	public function rules() {
		return array(
			array('id_pilote, id_hebergement, date_arrivee, date_depart, date_time_demande', 'required'),
			array('id_pilote, id_aeronef, id_hebergement, id_planning_stage', 'numerical', 'integerOnly'=>true),
			array('commentaire, licence_assurance_ffvv', 'safe'),
			array('id_aeronef, commentaire, licence_assurance_ffvv, id_planning_stage', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_stage, id_pilote, id_aeronef, id_hebergement, date_arrivee, date_depart, commentaire, date_time_demande, licence_assurance_ffvv, id_planning_stage', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPilote' => array(self::BELONGS_TO, 'Pilote', 'id_pilote'),
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
			'idHebergement' => array(self::BELONGS_TO, 'Hebergement', 'id_hebergement'),
			'idPlanningStage' => array(self::BELONGS_TO, 'PlanningStage', 'id_planning_stage'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_stage' => Yii::t('app', 'Id Stage'),
			'id_pilote' => null,
			'id_aeronef' => null,
			'id_hebergement' => null,
			'date_arrivee' => Yii::t('app', 'Date Arrivee'),
			'date_depart' => Yii::t('app', 'Date Depart'),
			'commentaire' => Yii::t('app', 'Commentaire'),
			'date_time_demande' => Yii::t('app', 'Date Time Demande'),
			'licence_assurance_ffvv' => Yii::t('app', 'Licence Assurance Ffvv'),
			'id_planning_stage' => null,
			'idPilote' => null,
			'idAeronef' => null,
			'idHebergement' => null,
			'idPlanningStage' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_stage', $this->id_stage);
		$criteria->compare('id_pilote', $this->id_pilote);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('id_hebergement', $this->id_hebergement);
		$criteria->compare('date_arrivee', $this->date_arrivee, true);
		$criteria->compare('date_depart', $this->date_depart, true);
		$criteria->compare('commentaire', $this->commentaire, true);
		$criteria->compare('date_time_demande', $this->date_time_demande, true);
		$criteria->compare('licence_assurance_ffvv', $this->licence_assurance_ffvv);
		$criteria->compare('id_planning_stage', $this->id_planning_stage);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
