<?php

/**
 * This is the model base class for the table "plan_group".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PlanGroup".
 *
 * Columns in table "plan_group" available as properties of the model,
 * followed by relations of table "plan_group" available as properties of the model.
 *
 * @property integer $id_plan_group
 * @property integer $id_planning
 * @property string $nom_group
 * @property string $concerne
 * @property string $type_membre
 * @property boolean $alerte
 * @property integer $nb_jours
 * @property boolean $actif
 * @property integer $id_group_depend
 * @property integer $ratio
 *
 * @property PlanJour[] $planJours
 * @property PlanGroup $idGroupDepend
 * @property PlanGroup[] $planGroups
 * @property Planning $idPlanning
 */
abstract class BasePlanGroup extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'plan_group';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PlanGroup|PlanGroups', $n);
	}

	public static function representingColumn() {
		return 'nom_group';
	}

	public function rules() {
		return array(
			array('id_planning, nom_group', 'required'),
			array('id_planning, nb_jours, id_group_depend, ratio', 'numerical', 'integerOnly'=>true),
			array('nom_group', 'length', 'max'=>60),
			array('concerne, type_membre', 'length', 'max'=>1),
			array('alerte, actif', 'safe'),
			array('concerne, type_membre, alerte, nb_jours, actif, id_group_depend, ratio', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_plan_group, id_planning, nom_group, concerne, type_membre, alerte, nb_jours, actif, id_group_depend, ratio', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'planJours' => array(self::HAS_MANY, 'PlanJour', 'id_plan_group'),
			'idGroupDepend' => array(self::BELONGS_TO, 'PlanGroup', 'id_group_depend'),
			'planGroups' => array(self::HAS_MANY, 'PlanGroup', 'id_group_depend'),
			'idPlanning' => array(self::BELONGS_TO, 'Planning', 'id_planning'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_plan_group' => Yii::t('app', 'Id Plan Group'),
			'id_planning' => null,
			'nom_group' => Yii::t('app', 'Nom Group'),
			'concerne' => Yii::t('app', 'Concerne'),
			'type_membre' => Yii::t('app', 'Type Membre'),
			'alerte' => Yii::t('app', 'Alerte'),
			'nb_jours' => Yii::t('app', 'Nb Jours'),
			'actif' => Yii::t('app', 'Actif'),
			'id_group_depend' => null,
			'ratio' => Yii::t('app', 'Ratio'),
			'planJours' => null,
			'idGroupDepend' => null,
			'planGroups' => null,
			'idPlanning' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_plan_group', $this->id_plan_group);
		$criteria->compare('id_planning', $this->id_planning);
		$criteria->compare('nom_group', $this->nom_group, true);
		$criteria->compare('concerne', $this->concerne, true);
		$criteria->compare('type_membre', $this->type_membre, true);
		$criteria->compare('alerte', $this->alerte);
		$criteria->compare('nb_jours', $this->nb_jours);
		$criteria->compare('actif', $this->actif);
		$criteria->compare('id_group_depend', $this->id_group_depend);
		$criteria->compare('ratio', $this->ratio);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
