<?php

/**
 * This is the model base class for the table "remorqueur_temps".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RemorqueurTemps".
 *
 * Columns in table "remorqueur_temps" available as properties of the model,
 * followed by relations of table "remorqueur_temps" available as properties of the model.
 *
 * @property integer $id_remorqeur_temps
 * @property integer $id_tarif_aeronef
 * @property integer $id_remorque
 * @property string $temps
 *
 * @property TarifAeronef $idTarifAeronef
 * @property Remorque $idRemorque
 */
abstract class BaseRemorqueurTemps extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'remorqueur_temps';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RemorqueurTemps|RemorqueurTemps', $n);
	}

	public static function representingColumn() {
		return 'temps';
	}

	public function rules() {
		return array(
			array('id_tarif_aeronef, id_remorque', 'required'),
			array('id_tarif_aeronef, id_remorque', 'numerical', 'integerOnly'=>true),
			array('temps', 'length', 'max'=>4),
			array('temps', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_remorqeur_temps, id_tarif_aeronef, id_remorque, temps', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idTarifAeronef' => array(self::BELONGS_TO, 'TarifAeronef', 'id_tarif_aeronef'),
			'idRemorque' => array(self::BELONGS_TO, 'Remorque', 'id_remorque'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_remorqeur_temps' => Yii::t('app', 'Id Remorqeur Temps'),
			'id_tarif_aeronef' => null,
			'id_remorque' => null,
			'temps' => Yii::t('app', 'Temps'),
			'idTarifAeronef' => null,
			'idRemorque' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_remorqeur_temps', $this->id_remorqeur_temps);
		$criteria->compare('id_tarif_aeronef', $this->id_tarif_aeronef);
		$criteria->compare('id_remorque', $this->id_remorque);
		$criteria->compare('temps', $this->temps, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
