<?php

/**
 * This is the model base class for the table "budget_chapitre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BudgetChapitre".
 *
 * Columns in table "budget_chapitre" available as properties of the model,
 * followed by relations of table "budget_chapitre" available as properties of the model.
 *
 * @property integer $id_budget_chapitre
 * @property string $prefix
 * @property string $code
 * @property string $libelle
 * @property boolean $titre
 * @property boolean $actif
 *
 * @property BudgetPrevi[] $budgetPrevis
 * @property BudgetValeur[] $budgetValeurs
 */
abstract class BaseBudgetChapitre extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'budget_chapitre';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BudgetChapitre|BudgetChapitres', $n);
	}

	public static function representingColumn() {
		return 'prefix';
	}

	public function rules() {
		return array(
			array('code, libelle', 'required'),
			array('prefix', 'length', 'max'=>1),
			array('code', 'length', 'max'=>8),
			array('libelle', 'length', 'max'=>120),
			array('titre, actif', 'safe'),
			array('prefix, titre, actif', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_budget_chapitre, prefix, code, libelle, titre, actif', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'budgetPrevis' => array(self::HAS_MANY, 'BudgetPrevi', 'id_budget_chapitre'),
			'budgetValeurs' => array(self::HAS_MANY, 'BudgetValeur', 'id_budget_chapitre'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_budget_chapitre' => Yii::t('app', 'Id Budget Chapitre'),
			'prefix' => Yii::t('app', 'Prefix'),
			'code' => Yii::t('app', 'Code'),
			'libelle' => Yii::t('app', 'Libelle'),
			'titre' => Yii::t('app', 'Titre'),
			'actif' => Yii::t('app', 'Actif'),
			'budgetPrevis' => null,
			'budgetValeurs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_budget_chapitre', $this->id_budget_chapitre);
		$criteria->compare('prefix', $this->prefix, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('libelle', $this->libelle, true);
		$criteria->compare('titre', $this->titre);
		$criteria->compare('actif', $this->actif);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
