<?php

/**
 * This is the model base class for the table "plan_jour".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PlanJour".
 *
 * Columns in table "plan_jour" available as properties of the model,
 * followed by relations of table "plan_jour" available as properties of the model.
 *
 * @property integer $id_plan_jour
 * @property integer $id_plan_group
 * @property string $date_jour
 * @property integer $nb_min
 * @property integer $nb_max
 * @property boolean $actif
 *
 * @property PlanGroup $idPlanGroup
 * @property PlanPart[] $planParts
 */
abstract class BasePlanJour extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'plan_jour';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PlanJour|PlanJours', $n);
	}

	public static function representingColumn() {
		return 'date_jour';
	}

	public function rules() {
		return array(
			array('id_plan_group, date_jour', 'required'),
			array('id_plan_group, nb_min, nb_max', 'numerical', 'integerOnly'=>true),
			array('actif', 'safe'),
			array('nb_min, nb_max, actif', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_plan_jour, id_plan_group, date_jour, nb_min, nb_max, actif', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPlanGroup' => array(self::BELONGS_TO, 'PlanGroup', 'id_plan_group'),
			'planParts' => array(self::HAS_MANY, 'PlanPart', 'id_plan_jour'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_plan_jour' => Yii::t('app', 'Id Plan Jour'),
			'id_plan_group' => null,
			'date_jour' => Yii::t('app', 'Date Jour'),
			'nb_min' => Yii::t('app', 'Nb Min'),
			'nb_max' => Yii::t('app', 'Nb Max'),
			'actif' => Yii::t('app', 'Actif'),
			'idPlanGroup' => null,
			'planParts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_plan_jour', $this->id_plan_jour);
		$criteria->compare('id_plan_group', $this->id_plan_group);
		$criteria->compare('date_jour', $this->date_jour, true);
		$criteria->compare('nb_min', $this->nb_min);
		$criteria->compare('nb_max', $this->nb_max);
		$criteria->compare('actif', $this->actif);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
