<?php

/**
 * This is the model base class for the table "moyen".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Moyen".
 *
 * Columns in table "moyen" available as properties of the model,
 * followed by relations of table "moyen" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_concours
 * @property integer $id_aeronef
 * @property integer $id_treuil
 * @property integer $id_pilote
 *
 * @property Concours $idConcours
 * @property Classe[] $classes
 */
abstract class BaseMoyen extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'moyen';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Moyen|Moyens', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id_concours', 'required'),
			array('id_concours, id_aeronef, id_treuil, id_pilote', 'numerical', 'integerOnly'=>true),
			array('id_aeronef, id_treuil, id_pilote', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_concours, id_aeronef, id_treuil, id_pilote', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idConcours' => array(self::BELONGS_TO, 'Concours', 'id_concours'),
			'classes' => array(self::MANY_MANY, 'Classe', 'moyen_prix(id_moyen, id_classe)'),
		);
	}

	public function pivotModels() {
		return array(
			'classes' => 'MoyenPrix',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_concours' => null,
			'id_aeronef' => Yii::t('app', 'Id Aeronef'),
			'id_treuil' => Yii::t('app', 'Id Treuil'),
			'id_pilote' => Yii::t('app', 'Id Pilote'),
			'idConcours' => null,
			'classes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_concours', $this->id_concours);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('id_treuil', $this->id_treuil);
		$criteria->compare('id_pilote', $this->id_pilote);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
