<?php

/**
 * This is the model base class for the table "type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Type".
 *
 * Columns in table "type" available as properties of the model,
 * followed by relations of table "type" available as properties of the model.
 *
 * @property integer $id_type
 * @property integer $id_modele
 * @property string $libelle
 *
 * @property Aeronef[] $aeronefs
 * @property Modele $idModele
 */
abstract class BaseType extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Type|Types', $n);
	}

	public static function representingColumn() {
		return 'libelle';
	}

	public function rules() {
		return array(
			array('id_modele, libelle', 'required'),
			array('id_modele', 'numerical', 'integerOnly'=>true),
			array('libelle', 'length', 'max'=>60),
			array('id_type, id_modele, libelle', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'aeronefs' => array(self::HAS_MANY, 'Aeronef', 'id_type'),
			'idModele' => array(self::BELONGS_TO, 'Modele', 'id_modele'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_type' => Yii::t('app', 'Id Type'),
			'id_modele' => null,
			'libelle' => Yii::t('app', 'Libelle'),
			'aeronefs' => null,
			'idModele' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_type', $this->id_type);
		$criteria->compare('id_modele', $this->id_modele);
		$criteria->compare('libelle', $this->libelle, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
