<?php

/**
 * This is the model base class for the table "courriel_joint".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CourrielJoint".
 *
 * Columns in table "courriel_joint" available as properties of the model,
 * followed by relations of table "courriel_joint" available as properties of the model.
 *
 * @property integer $id_courriel_joint
 * @property integer $id_feuille
 * @property integer $id_courriel
 *
 * @property Courriel $idCourriel
 * @property Feuille $idFeuille
 */
abstract class BaseCourrielJoint extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'courriel_joint';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CourrielJoint|CourrielJoints', $n);
	}

	public static function representingColumn() {
		return 'id_courriel_joint';
	}

	public function rules() {
		return array(
			array('id_feuille, id_courriel', 'required'),
			array('id_feuille, id_courriel', 'numerical', 'integerOnly'=>true),
			array('id_courriel_joint, id_feuille, id_courriel', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCourriel' => array(self::BELONGS_TO, 'Courriel', 'id_courriel'),
			'idFeuille' => array(self::BELONGS_TO, 'Feuille', 'id_feuille'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_courriel_joint' => Yii::t('app', 'Id Courriel Joint'),
			'id_feuille' => null,
			'id_courriel' => null,
			'idCourriel' => null,
			'idFeuille' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_courriel_joint', $this->id_courriel_joint);
		$criteria->compare('id_feuille', $this->id_feuille);
		$criteria->compare('id_courriel', $this->id_courriel);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
