<?php

/**
 * This is the model base class for the table "jour_ferie".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "JourFerie".
 *
 * Columns in table "jour_ferie" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_jour_ferie
 * @property string $date_jour
 *
 */
abstract class BaseJourFerie extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'jour_ferie';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'JourFerie|JourFeries', $n);
	}

	public static function representingColumn() {
		return 'date_jour';
	}

	public function rules() {
		return array(
			array('date_jour', 'required'),
			array('id_jour_ferie, date_jour', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_jour_ferie' => Yii::t('app', 'Id Jour Ferie'),
			'date_jour' => Yii::t('app', 'Date Jour'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_jour_ferie', $this->id_jour_ferie);
		$criteria->compare('date_jour', $this->date_jour, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
