<?php

/**
 * This is the model base class for the table "stat_ffvv".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StatFfvv".
 *
 * Columns in table "stat_ffvv" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_stat_ffvv
 * @property integer $annee
 * @property integer $mois
 * @property string $hrs_moins25
 * @property string $hrs_plus25
 * @property string $hrs_etrangers
 * @property string $hrs_stagiaires
 * @property integer $remo_moins25
 * @property integer $remo_plus25
 * @property integer $remo_etrangers
 * @property integer $remo_stagiaires
 * @property integer $treuil_moins25
 * @property integer $treuil_plus25
 * @property integer $treuil_etrangers
 * @property integer $treuil_stagiaires
 * @property integer $lache_moins25
 * @property integer $lache_plus25
 * @property integer $bpp_theorique_moins25
 * @property integer $bpp_theorique_plus25
 * @property integer $bpp_pratique_moins25
 * @property integer $bpp_pratique_plus25
 * @property integer $campagne_moins25
 * @property integer $campagne_plus25
 * @property integer $km_moins25
 * @property integer $km_plus25
 * @property integer $licence_pleine_moins25
 * @property integer $licence_pleine_plus25
 * @property integer $licence_courte_moins25
 * @property integer $licence_courte_plus25
 * @property integer $vi
 *
 */
abstract class BaseStatFfvv extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'stat_ffvv';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StatFfvv|StatFfvvs', $n);
	}

	public static function representingColumn() {
		return 'id_stat_ffvv';
	}

	public function rules() {
		return array(
			array('annee', 'required'),
			array('annee, mois, remo_moins25, remo_plus25, remo_etrangers, remo_stagiaires, treuil_moins25, treuil_plus25, treuil_etrangers, treuil_stagiaires, lache_moins25, lache_plus25, bpp_theorique_moins25, bpp_theorique_plus25, bpp_pratique_moins25, bpp_pratique_plus25, campagne_moins25, campagne_plus25, km_moins25, km_plus25, licence_pleine_moins25, licence_pleine_plus25, licence_courte_moins25, licence_courte_plus25, vi', 'numerical', 'integerOnly'=>true),
			array('hrs_moins25, hrs_plus25, hrs_etrangers, hrs_stagiaires', 'safe'),
			array('mois, hrs_moins25, hrs_plus25, hrs_etrangers, hrs_stagiaires, remo_moins25, remo_plus25, remo_etrangers, remo_stagiaires, treuil_moins25, treuil_plus25, treuil_etrangers, treuil_stagiaires, lache_moins25, lache_plus25, bpp_theorique_moins25, bpp_theorique_plus25, bpp_pratique_moins25, bpp_pratique_plus25, campagne_moins25, campagne_plus25, km_moins25, km_plus25, licence_pleine_moins25, licence_pleine_plus25, licence_courte_moins25, licence_courte_plus25, vi', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_stat_ffvv, annee, mois, hrs_moins25, hrs_plus25, hrs_etrangers, hrs_stagiaires, remo_moins25, remo_plus25, remo_etrangers, remo_stagiaires, treuil_moins25, treuil_plus25, treuil_etrangers, treuil_stagiaires, lache_moins25, lache_plus25, bpp_theorique_moins25, bpp_theorique_plus25, bpp_pratique_moins25, bpp_pratique_plus25, campagne_moins25, campagne_plus25, km_moins25, km_plus25, licence_pleine_moins25, licence_pleine_plus25, licence_courte_moins25, licence_courte_plus25, vi', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_stat_ffvv' => Yii::t('app', 'Id Stat Ffvv'),
			'annee' => Yii::t('app', 'Annee'),
			'mois' => Yii::t('app', 'Mois'),
			'hrs_moins25' => Yii::t('app', 'Hrs Moins25'),
			'hrs_plus25' => Yii::t('app', 'Hrs Plus25'),
			'hrs_etrangers' => Yii::t('app', 'Hrs Etrangers'),
			'hrs_stagiaires' => Yii::t('app', 'Hrs Stagiaires'),
			'remo_moins25' => Yii::t('app', 'Remo Moins25'),
			'remo_plus25' => Yii::t('app', 'Remo Plus25'),
			'remo_etrangers' => Yii::t('app', 'Remo Etrangers'),
			'remo_stagiaires' => Yii::t('app', 'Remo Stagiaires'),
			'treuil_moins25' => Yii::t('app', 'Treuil Moins25'),
			'treuil_plus25' => Yii::t('app', 'Treuil Plus25'),
			'treuil_etrangers' => Yii::t('app', 'Treuil Etrangers'),
			'treuil_stagiaires' => Yii::t('app', 'Treuil Stagiaires'),
			'lache_moins25' => Yii::t('app', 'Lache Moins25'),
			'lache_plus25' => Yii::t('app', 'Lache Plus25'),
			'bpp_theorique_moins25' => Yii::t('app', 'Bpp Theorique Moins25'),
			'bpp_theorique_plus25' => Yii::t('app', 'Bpp Theorique Plus25'),
			'bpp_pratique_moins25' => Yii::t('app', 'Bpp Pratique Moins25'),
			'bpp_pratique_plus25' => Yii::t('app', 'Bpp Pratique Plus25'),
			'campagne_moins25' => Yii::t('app', 'Campagne Moins25'),
			'campagne_plus25' => Yii::t('app', 'Campagne Plus25'),
			'km_moins25' => Yii::t('app', 'Km Moins25'),
			'km_plus25' => Yii::t('app', 'Km Plus25'),
			'licence_pleine_moins25' => Yii::t('app', 'Licence Pleine Moins25'),
			'licence_pleine_plus25' => Yii::t('app', 'Licence Pleine Plus25'),
			'licence_courte_moins25' => Yii::t('app', 'Licence Courte Moins25'),
			'licence_courte_plus25' => Yii::t('app', 'Licence Courte Plus25'),
			'vi' => Yii::t('app', 'Vi'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_stat_ffvv', $this->id_stat_ffvv);
		$criteria->compare('annee', $this->annee);
		$criteria->compare('mois', $this->mois);
		$criteria->compare('hrs_moins25', $this->hrs_moins25, true);
		$criteria->compare('hrs_plus25', $this->hrs_plus25, true);
		$criteria->compare('hrs_etrangers', $this->hrs_etrangers, true);
		$criteria->compare('hrs_stagiaires', $this->hrs_stagiaires, true);
		$criteria->compare('remo_moins25', $this->remo_moins25);
		$criteria->compare('remo_plus25', $this->remo_plus25);
		$criteria->compare('remo_etrangers', $this->remo_etrangers);
		$criteria->compare('remo_stagiaires', $this->remo_stagiaires);
		$criteria->compare('treuil_moins25', $this->treuil_moins25);
		$criteria->compare('treuil_plus25', $this->treuil_plus25);
		$criteria->compare('treuil_etrangers', $this->treuil_etrangers);
		$criteria->compare('treuil_stagiaires', $this->treuil_stagiaires);
		$criteria->compare('lache_moins25', $this->lache_moins25);
		$criteria->compare('lache_plus25', $this->lache_plus25);
		$criteria->compare('bpp_theorique_moins25', $this->bpp_theorique_moins25);
		$criteria->compare('bpp_theorique_plus25', $this->bpp_theorique_plus25);
		$criteria->compare('bpp_pratique_moins25', $this->bpp_pratique_moins25);
		$criteria->compare('bpp_pratique_plus25', $this->bpp_pratique_plus25);
		$criteria->compare('campagne_moins25', $this->campagne_moins25);
		$criteria->compare('campagne_plus25', $this->campagne_plus25);
		$criteria->compare('km_moins25', $this->km_moins25);
		$criteria->compare('km_plus25', $this->km_plus25);
		$criteria->compare('licence_pleine_moins25', $this->licence_pleine_moins25);
		$criteria->compare('licence_pleine_plus25', $this->licence_pleine_plus25);
		$criteria->compare('licence_courte_moins25', $this->licence_courte_moins25);
		$criteria->compare('licence_courte_plus25', $this->licence_courte_plus25);
		$criteria->compare('vi', $this->vi);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
