<?php

/**
 * This is the model base class for the table "aeronef_situation".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AeronefSituation".
 *
 * Columns in table "aeronef_situation" available as properties of the model,
 * followed by relations of table "aeronef_situation" available as properties of the model.
 *
 * @property integer $id_aeronef_situation
 * @property integer $id_aeronef
 * @property string $date_application
 * @property string $situation
 * @property integer $id_tarif_cat_aeronef
 *
 * @property Aeronef $idAeronef
 * @property TarifCatAeronef $idTarifCatAeronef
 * @property AeronefRetrocession $aeronefRetrocession
 * @property Annuaire[] $annuaires
 */
abstract class BaseAeronefSituation extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'aeronef_situation';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AeronefSituation|AeronefSituations', $n);
	}

	public static function representingColumn() {
		return 'date_application';
	}

	public function rules() {
		return array(
			array('date_application, id_tarif_cat_aeronef', 'required'),
			array('id_tarif_cat_aeronef', 'numerical', 'integerOnly'=>true),
			array('situation', 'length', 'max'=>1),
			array('situation', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_aeronef_situation, id_aeronef, date_application, situation, id_tarif_cat_aeronef', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
			'idTarifCatAeronef' => array(self::BELONGS_TO, 'TarifCatAeronef', 'id_tarif_cat_aeronef'),
			'aeronefRetrocession' => array(self::HAS_ONE, 'AeronefRetrocession', 'id_aeronef_situation'),
			'annuaires' => array(self::MANY_MANY, 'Annuaire', 'aeronef_situation_benef(id_aeronef_situation, id_annu)'),
		);
	}

	public function pivotModels() {
		return array(
			'annuaires' => 'AeronefSituationBenef',
		);
	}

	public function attributeLabels() {
		return array(
			'id_aeronef_situation' => Yii::t('app', 'Id Aeronef Situation'),
			'id_aeronef' => null,
			'date_application' => Yii::t('app', 'Date Application'),
			'situation' => Yii::t('app', 'Situation'),
			'id_tarif_cat_aeronef' => null,
			'idAeronef' => null,
			'idTarifCatAeronef' => null,
			'aeronefRetrocession' => null,
			'annuaires' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_aeronef_situation', $this->id_aeronef_situation);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('date_application', $this->date_application, true);
		$criteria->compare('situation', $this->situation, true);
		$criteria->compare('id_tarif_cat_aeronef', $this->id_tarif_cat_aeronef);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
