<?php

/**
 * This is the model base class for the table "forfait_modele_aeronef_complement".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ForfaitModeleAeronefComplement".
 *
 * Columns in table "forfait_modele_aeronef_complement" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_forfait_modele
 * @property integer $id_aeronef
 * @property string $prix_heure_cellule
 * @property string $prix_unite_cellule
 * @property string $prix_heure_moteur
 * @property string $prix_unite_moteur
 * @property string $prix_heure_remorque
 * @property string $prix_unite_remorque
 * @property string $prix_unite_treuillee
 * @property string $prix_heure_simu
 * @property string $prix_unite_simu
 *
 */
abstract class BaseForfaitModeleAeronefComplement extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'forfait_modele_aeronef_complement';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ForfaitModeleAeronefComplement|ForfaitModeleAeronefComplements', $n);
	}

	public static function representingColumn() {
		return array(
			'id_forfait_modele',
			'id_aeronef',
		);
	}

	public function rules() {
		return array(
			array('id_forfait_modele, id_aeronef', 'required'),
			array('id_forfait_modele, id_aeronef', 'numerical', 'integerOnly'=>true),
			array('prix_heure_cellule, prix_unite_cellule, prix_heure_moteur, prix_unite_moteur, prix_heure_remorque, prix_unite_remorque, prix_unite_treuillee, prix_heure_simu, prix_unite_simu', 'length', 'max'=>10),
			array('prix_heure_cellule, prix_unite_cellule, prix_heure_moteur, prix_unite_moteur, prix_heure_remorque, prix_unite_remorque, prix_unite_treuillee, prix_heure_simu, prix_unite_simu', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_forfait_modele, id_aeronef, prix_heure_cellule, prix_unite_cellule, prix_heure_moteur, prix_unite_moteur, prix_heure_remorque, prix_unite_remorque, prix_unite_treuillee, prix_heure_simu, prix_unite_simu', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_forfait_modele' => null,
			'id_aeronef' => null,
			'prix_heure_cellule' => Yii::t('app', 'Prix Heure Cellule'),
			'prix_unite_cellule' => Yii::t('app', 'Prix Unite Cellule'),
			'prix_heure_moteur' => Yii::t('app', 'Prix Heure Moteur'),
			'prix_unite_moteur' => Yii::t('app', 'Prix Unite Moteur'),
			'prix_heure_remorque' => Yii::t('app', 'Prix Heure Remorque'),
			'prix_unite_remorque' => Yii::t('app', 'Prix Unite Remorque'),
			'prix_unite_treuillee' => Yii::t('app', 'Prix Unite Treuillee'),
			'prix_heure_simu' => Yii::t('app', 'Prix Heure Simu'),
			'prix_unite_simu' => Yii::t('app', 'Prix Unite Simu'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_forfait_modele', $this->id_forfait_modele);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('prix_heure_cellule', $this->prix_heure_cellule, true);
		$criteria->compare('prix_unite_cellule', $this->prix_unite_cellule, true);
		$criteria->compare('prix_heure_moteur', $this->prix_heure_moteur, true);
		$criteria->compare('prix_unite_moteur', $this->prix_unite_moteur, true);
		$criteria->compare('prix_heure_remorque', $this->prix_heure_remorque, true);
		$criteria->compare('prix_unite_remorque', $this->prix_unite_remorque, true);
		$criteria->compare('prix_unite_treuillee', $this->prix_unite_treuillee, true);
		$criteria->compare('prix_heure_simu', $this->prix_heure_simu, true);
		$criteria->compare('prix_unite_simu', $this->prix_unite_simu, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
