<?php

/**
 * This is the model base class for the table "civilite".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Civilite".
 *
 * Columns in table "civilite" available as properties of the model,
 * followed by relations of table "civilite" available as properties of the model.
 *
 * @property string $civilite
 *
 * @property Annuaire[] $annuaires
 * @property DemandeStage[] $demandeStages
 */
abstract class BaseCivilite extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'civilite';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Civilite|Civilites', $n);
	}

	public static function representingColumn() {
		return 'civilite';
	}

	public function rules() {
		return array(
			array('civilite', 'required'),
			array('civilite', 'length', 'max'=>5),
			array('civilite', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'annuaires' => array(self::HAS_MANY, 'Annuaire', 'civilite'),
			'demandeStages' => array(self::HAS_MANY, 'DemandeStage', 'civilite'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'civilite' => Yii::t('app', 'Civilite'),
			'annuaires' => null,
			'demandeStages' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('civilite', $this->civilite, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
