<?php

/**
 * This is the model base class for the table "fabriquant".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Fabriquant".
 *
 * Columns in table "fabriquant" available as properties of the model,
 * followed by relations of table "fabriquant" available as properties of the model.
 *
 * @property integer $id_fabriquant
 * @property integer $id_annu
 *
 * @property Modele[] $modeles
 * @property Annuaire $idAnnu
 */
abstract class BaseFabriquant extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'fabriquant';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Fabriquant|Fabriquants', $n);
	}

	public static function representingColumn() {
		return 'id_fabriquant';
	}

	public function rules() {
		return array(
			array('id_annu', 'required'),
			array('id_annu', 'numerical', 'integerOnly'=>true),
			array('id_fabriquant, id_annu', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'modeles' => array(self::HAS_MANY, 'Modele', 'id_fabriquant'),
			'idAnnu' => array(self::BELONGS_TO, 'Annuaire', 'id_annu'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_fabriquant' => Yii::t('app', 'Id Fabriquant'),
			'id_annu' => null,
			'modeles' => null,
			'idAnnu' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_fabriquant', $this->id_fabriquant);
		$criteria->compare('id_annu', $this->id_annu);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
