<?php

/**
 * This is the model base class for the table "compte_gnav".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompteGnav".
 *
 * Columns in table "compte_gnav" available as properties of the model,
 * followed by relations of table "compte_gnav" available as properties of the model.
 *
 * @property integer $id_compte_gnav
 * @property string $code_gnav
 * @property string $mot_de_passe
 * @property integer $id_annu
 *
 * @property Aeronef[] $aeronefs
 * @property Annuaire $idAnnu
 */
abstract class BaseCompteGnav extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'compte_gnav';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CompteGnav|CompteGnavs', $n);
	}

	public static function representingColumn() {
		return 'code_gnav';
	}

	public function rules() {
		return array(
			array('code_gnav, mot_de_passe, id_annu', 'required'),
			array('id_annu', 'numerical', 'integerOnly'=>true),
			array('code_gnav', 'length', 'max'=>5),
			array('mot_de_passe', 'length', 'max'=>10),
			array('id_compte_gnav, code_gnav, mot_de_passe, id_annu', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'aeronefs' => array(self::HAS_MANY, 'Aeronef', 'id_compte_gnav'),
			'idAnnu' => array(self::BELONGS_TO, 'Annuaire', 'id_annu'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_compte_gnav' => Yii::t('app', 'Id Compte Gnav'),
			'code_gnav' => Yii::t('app', 'Code Gnav'),
			'mot_de_passe' => Yii::t('app', 'Mot De Passe'),
			'id_annu' => null,
			'aeronefs' => null,
			'idAnnu' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_compte_gnav', $this->id_compte_gnav);
		$criteria->compare('code_gnav', $this->code_gnav, true);
		$criteria->compare('mot_de_passe', $this->mot_de_passe, true);
		$criteria->compare('id_annu', $this->id_annu);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
