<?php

/**
 * This is the model base class for the table "courriel_to".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CourrielTo".
 *
 * Columns in table "courriel_to" available as properties of the model,
 * followed by relations of table "courriel_to" available as properties of the model.
 *
 * @property integer $id_courriel_to
 * @property integer $id_courriel
 * @property string $to_cc_bcc
 * @property string $courriel
 *
 * @property Courriel $idCourriel
 */
abstract class BaseCourrielTo extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'courriel_to';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CourrielTo|CourrielTos', $n);
	}

	public static function representingColumn() {
		return 'to_cc_bcc';
	}

	public function rules() {
		return array(
			array('id_courriel, courriel', 'required'),
			array('id_courriel', 'numerical', 'integerOnly'=>true),
			array('to_cc_bcc', 'length', 'max'=>1),
			array('courriel', 'length', 'max'=>255),
			array('to_cc_bcc', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_courriel_to, id_courriel, to_cc_bcc, courriel', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCourriel' => array(self::BELONGS_TO, 'Courriel', 'id_courriel'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_courriel_to' => Yii::t('app', 'Id Courriel To'),
			'id_courriel' => null,
			'to_cc_bcc' => Yii::t('app', 'To Cc Bcc'),
			'courriel' => Yii::t('app', 'Courriel'),
			'idCourriel' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_courriel_to', $this->id_courriel_to);
		$criteria->compare('id_courriel', $this->id_courriel);
		$criteria->compare('to_cc_bcc', $this->to_cc_bcc, true);
		$criteria->compare('courriel', $this->courriel, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
