<?php

/**
 * This is the model base class for the table "planning_stage".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PlanningStage".
 *
 * Columns in table "planning_stage" available as properties of the model,
 * followed by relations of table "planning_stage" available as properties of the model.
 *
 * @property integer $id_planning_stage
 * @property string $date_debut
 * @property string $date_fin
 * @property string $nom_stage
 * @property string $programme
 *
 * @property Stage[] $stages
 * @property DemandeStage[] $demandeStages
 */
abstract class BasePlanningStage extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'planning_stage';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PlanningStage|PlanningStages', $n);
	}

	public static function representingColumn() {
		return 'date_debut';
	}

	public function rules() {
		return array(
			array('date_debut, date_fin, nom_stage, programme', 'required'),
			array('nom_stage', 'length', 'max'=>255),
			array('id_planning_stage, date_debut, date_fin, nom_stage, programme', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'stages' => array(self::HAS_MANY, 'Stage', 'id_planning_stage'),
			'demandeStages' => array(self::HAS_MANY, 'DemandeStage', 'id_planning_stage'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_planning_stage' => Yii::t('app', 'Id Planning Stage'),
			'date_debut' => Yii::t('app', 'Date Debut'),
			'date_fin' => Yii::t('app', 'Date Fin'),
			'nom_stage' => Yii::t('app', 'Nom Stage'),
			'programme' => Yii::t('app', 'Programme'),
			'stages' => null,
			'demandeStages' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_planning_stage', $this->id_planning_stage);
		$criteria->compare('date_debut', $this->date_debut, true);
		$criteria->compare('date_fin', $this->date_fin, true);
		$criteria->compare('nom_stage', $this->nom_stage, true);
		$criteria->compare('programme', $this->programme, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
