<?php

/**
 * This is the model base class for the table "ligne_ordre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LigneOrdre".
 *
 * Columns in table "ligne_ordre" available as properties of the model,
 * followed by relations of table "ligne_ordre" available as properties of the model.
 *
 * @property integer $id_ligne
 * @property string $date_jour
 * @property integer $ordre
 *
 * @property Ligne $idLigne
 */
abstract class BaseLigneOrdre extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ligne_ordre';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LigneOrdre|LigneOrdres', $n);
	}

	public static function representingColumn() {
		return 'date_jour';
	}

	public function rules() {
		return array(
			array('id_ligne, date_jour', 'required'),
			array('id_ligne, ordre', 'numerical', 'integerOnly'=>true),
			array('ordre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_ligne, date_jour, ordre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idLigne' => array(self::BELONGS_TO, 'Ligne', 'id_ligne'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_ligne' => null,
			'date_jour' => Yii::t('app', 'Date Jour'),
			'ordre' => Yii::t('app', 'Ordre'),
			'idLigne' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_ligne', $this->id_ligne);
		$criteria->compare('date_jour', $this->date_jour, true);
		$criteria->compare('ordre', $this->ordre);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
