<?php

/**
 * This is the model base class for the table "stat_ffvv_aeronef".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StatFfvvAeronef".
 *
 * Columns in table "stat_ffvv_aeronef" available as properties of the model,
 * followed by relations of table "stat_ffvv_aeronef" available as properties of the model.
 *
 * @property integer $id_stat_ffvv_aeronef
 * @property integer $id_aeronef
 * @property integer $annee
 * @property integer $mois
 * @property string $hrs_planeur
 * @property string $hrs_remorquage
 *
 * @property Aeronef $idAeronef
 */
abstract class BaseStatFfvvAeronef extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'stat_ffvv_aeronef';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StatFfvvAeronef|StatFfvvAeronefs', $n);
	}

	public static function representingColumn() {
		return 'id_stat_ffvv_aeronef';
	}

	public function rules() {
		return array(
			array('id_aeronef, annee, mois', 'required'),
			array('id_aeronef, annee, mois', 'numerical', 'integerOnly'=>true),
			array('hrs_planeur, hrs_remorquage', 'safe'),
			array('hrs_planeur, hrs_remorquage', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_stat_ffvv_aeronef, id_aeronef, annee, mois, hrs_planeur, hrs_remorquage', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idAeronef' => array(self::BELONGS_TO, 'Aeronef', 'id_aeronef'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_stat_ffvv_aeronef' => Yii::t('app', 'Id Stat Ffvv Aeronef'),
			'id_aeronef' => null,
			'annee' => Yii::t('app', 'Annee'),
			'mois' => Yii::t('app', 'Mois'),
			'hrs_planeur' => Yii::t('app', 'Hrs Planeur'),
			'hrs_remorquage' => Yii::t('app', 'Hrs Remorquage'),
			'idAeronef' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_stat_ffvv_aeronef', $this->id_stat_ffvv_aeronef);
		$criteria->compare('id_aeronef', $this->id_aeronef);
		$criteria->compare('annee', $this->annee);
		$criteria->compare('mois', $this->mois);
		$criteria->compare('hrs_planeur', $this->hrs_planeur, true);
		$criteria->compare('hrs_remorquage', $this->hrs_remorquage, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
