<?php

/**
 * This is the model base class for the table "moyen_prix".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MoyenPrix".
 *
 * Columns in table "moyen_prix" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_moyen
 * @property integer $id_classe
 * @property integer $prix
 *
 */
abstract class BaseMoyenPrix extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'moyen_prix';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MoyenPrix|MoyenPrixes', $n);
	}

	public static function representingColumn() {
		return array(
			'id_moyen',
			'id_classe',
		);
	}

	public function rules() {
		return array(
			array('id_moyen, id_classe', 'required'),
			array('id_moyen, id_classe, prix', 'numerical', 'integerOnly'=>true),
			array('prix', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_moyen, id_classe, prix', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_moyen' => null,
			'id_classe' => null,
			'prix' => Yii::t('app', 'Prix'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_moyen', $this->id_moyen);
		$criteria->compare('id_classe', $this->id_classe);
		$criteria->compare('prix', $this->prix);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
