<?php

/**
 * This is the model base class for the table "menu_droit".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MenuDroit".
 *
 * Columns in table "menu_droit" available as properties of the model,
 * followed by relations of table "menu_droit" available as properties of the model.
 *
 * @property integer $id_menu_droit
 * @property integer $id_utilisateur
 * @property integer $id_menu
 *
 * @property Menu $idMenu
 * @property Utilisateur $idUtilisateur
 */
abstract class BaseMenuDroit extends GxActiveRecord {

	public function getDbConnection()
	{
		return Yii::app()->givav;
	}
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'menu_droit';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MenuDroit|MenuDroits', $n);
	}

	public static function representingColumn() {
		return 'id_menu_droit';
	}

	public function rules() {
		return array(
			array('id_utilisateur, id_menu', 'required'),
			array('id_utilisateur, id_menu', 'numerical', 'integerOnly'=>true),
			array('id_menu_droit, id_utilisateur, id_menu', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idMenu' => array(self::BELONGS_TO, 'Menu', 'id_menu'),
			'idUtilisateur' => array(self::BELONGS_TO, 'Utilisateur', 'id_utilisateur'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_menu_droit' => Yii::t('app', 'Id Menu Droit'),
			'id_utilisateur' => null,
			'id_menu' => null,
			'idMenu' => null,
			'idUtilisateur' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_menu_droit', $this->id_menu_droit);
		$criteria->compare('id_utilisateur', $this->id_utilisateur);
		$criteria->compare('id_menu', $this->id_menu);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
